AlgebraicJulia/Catlab.jl

src/doctrines/AdditiveMonoidal.jl
src/doctrines/Monoidal.jl
test/doctrines/AdditiveMonoidal.jl
test/doctrines/Monoidal.jl

Moved Cocartesian, FreeCocartesian, and MonoidalCategoryWithCodiagonals

Added tests for and added to Additive Monoidal Categories

---

src/linear_algebra/GLA.jl
test/linear_algebra/GLA.jl

Added more tests and now they pass. Avoids the stochastic failure by only doing power method on a larger matrices where the P(failure) is smaller.

GLA gmres test

---

src/core/GAT.jl
src/doctrines/Category.jl
src/doctrines/Monoidal.jl
src/experimental/AlgebraicNets.jl
src/experimental/MathFormulas.jl
test/core/GAT.jl
test/core/Syntax.jl
test/doctrines/Category.jl
test/doctrines/Monoidal.jl

Remove functions from signature/theory definitions

---

docs/src/index.md

add snippet from slack explaining the history of GATs

Update index.md with history of GATs

---

src/doctrines/Doctrines.jl
src/doctrines/Preorders.jl
test/doctrines/Doctrines.jl
test/doctrines/Preorders.jl

Preorders and thin categories, part 2

---

experiments/Markov/Project.toml
experiments/Markov/src/Markov.jl
experiments/Markov/src/StochExpr.jl
experiments/Markov/test/StochMapsExpr.jl
experiments/Markov/test/runtests.jl

ENH: Implement Stochastic Maps as GATExprs

---

.github/workflows/docs.yml
.github/workflows/experiments.yml
.github/workflows/tests.yml

Test experiments in GitHub CI

---

README.md

I'd like to start encouraging people to use Zulip, rather than Slack. Any objections?

Link to Catlab channel on Julia Zulip

---

src/categorical_algebra/FinSets.jl
src/theories/AdditiveMonoidal.jl
src/theories/Limits.jl
src/theories/Monoidal.jl
src/theories/Theories.jl
test/theories/AdditiveMonoidal.jl

Towards #171. I haven't yet implemented the other, more general interface for (co)limits, but I'd like to get this merged because it has some tweaks/improvements to other GATs and I don't want to deal with merge conflicts later.

GATs for categories with (co)limits

---

src/categorical_algebra/ShapeDiagrams.jl

As I am working on [AlgebraicPetri.jl](https://github.com/AlgebraicJulia/AlgebraicPetri.jl), I am putting together an implementation of decorated cospans in Catlab to help work with open systems.

Implementation of Decorated Cospans

---

src/categorical_algebra/FinSets.jl
src/categorical_algebra/ShapeDiagrams.jl
test/categorical_algebra/FinSets.jl
test/categorical_algebra/ShapeDiagrams.jl

I don't want to merge this yet, but I would like some feedback about my current approach to n-ary (co)products. My plan is to build arbitrary limits on top of n-ary (co)products and n-ary (co)equalizers.

ENH: n-ary (co)products

---

src/categorical_algebra/CSets.jl
src/categorical_algebra/Graphs.jl
src/wiring_diagrams/Undirected.jl
test/categorical_algebra/CSets.jl
test/categorical_algebra/Graphs.jl

Unique and non-unique indexing of data in C-sets

---

docs/src/apis/graphics.md
docs/src/apis/programs.md
docs/src/apis/wiring_diagrams.md
src/programs/Programs.jl
src/programs/RelationalPrograms.jl
src/wiring_diagrams/Undirected.jl
test/programs/Programs.jl
test/programs/RelationalPrograms.jl
test/wiring_diagrams/Undirected.jl

It turns out that a tensor network---a general contraction of a set of tensors---is *exactly* the data of an undirected wiring diagram, at least up to renaming of variables. This PR adds:
- Macro `@tensor_network` to parse an undirected wiring diagram from a tensor contraction expression
- Function `compile_tensor` to generate and compile a tensor expression from an undirected wiring diagram, intended for use with packages like [TensorOperations.jl](https://github.com/Jutho/TensorOperations.jl)
The two operations are essentially inverse to each other. I think it makes sense to include this functionality in Catlab itself because the connection is fundamental and no special dependencies are needed.

Tensor notation for undirected wiring diagrams

---

src/categorical_algebra/FinRelations.jl
src/categorical_algebra/FinSets.jl
test/categorical_algebra/FinSets.jl

Use FunctionWrappers for FinSets and FinRelations

---

.github/workflows/codecov.yml
docs/literate/graphics/layouts_vs_drawings.jl

Code coverage hopefully will include literate tests

More Exhaustive Code Coverage Tests

---

src/graphics/GraphvizWiringDiagrams.jl
test/graphics/GraphvizWiringDiagrams.jl

Option to label boxes/junctions in Graphviz UWDs by number

---

.github/workflows/codecov.yml
codecov.yml

Not the ideal configuration but should at least eliminate the noise from the code coverage bot.

Add codecov.yml.

---

src/categorical_algebra/CSets.jl
src/categorical_algebra/FreeDiagrams.jl
src/categorical_algebra/Graphs.jl
src/wiring_diagrams/Undirected.jl

Old CSetType function and friends

---

src/programs/RelationalPrograms.jl
src/theories/Monoidal.jl
src/wiring_diagrams/Expressions.jl
src/wiring_diagrams/MonoidalUndirected.jl
src/wiring_diagrams/Undirected.jl
test/programs/RelationalPrograms.jl
test/wiring_diagrams/Expressions.jl
test/wiring_diagrams/MonoidalUndirected.jl

Resolves #218. Also includes miscellaneous cleanup related to UWDs.
I began this awhile ago but was blocked by the poor handling of data types in the original C-sets implementation. Thankfully that was resolved by the C-sets refactor!

Convert morphism expressions to UWDs

---

src/categorical_algebra/FinSets.jl
src/categorical_algebra/Limits.jl
test/categorical_algebra/FinSets.jl

Covers all cases except (co)limits over a general diagram (`FreeDiagram`).

Universal properties of limits and colimits in FinSet

---

src/categorical_algebra/CSetMorphisms.jl
src/categorical_algebra/CategoricalAlgebra.jl
src/theories/Schema.jl
test/categorical_algebra/CSetMorphisms.jl
test/categorical_algebra/CategoricalAlgebra.jl

- Data structure for C-set morphisms (natural transformations)
- Function to check naturality of transformation
- Basic category structure: composition and identities

C-set morphisms

---

src/theories/Monoidal.jl
src/theories/MonoidalAdditive.jl

Converts several `@signature`s into `@theory` declarations with axioms.

Axioms for SMCs with diagonals

---

src/categorical_algebra/CSetDataStructures.jl
test/categorical_algebra/CSetDataStructures.jl

Resolves #294. See the unit tests for examples.

Composite morphisms and attributes in C-set accessors

---

src/categorical_algebra/CSetDataStructures.jl
test/categorical_algebra/CSetDataStructures.jl
test/graphs/BasicGraphs.jl

With #293 implemented, we can finally resolve #199 in a satisfactory way. The previous fix was in #204.

Roll back added C-set parts on error

---

src/categorical_algebra/CSetDataStructures.jl
src/wiring_diagrams/MonoidalUndirected.jl
test/categorical_algebra/CSetDataStructures.jl

Resolves #307 and also fills out the API to fix #310.

Return views from C-set accessors where appropriate

---

src/categorical_algebra/CSets.jl
src/categorical_algebra/FinSets.jl
src/categorical_algebra/FreeDiagrams.jl
src/wiring_diagrams/Algorithms.jl
test/categorical_algebra/CSets.jl
test/categorical_algebra/FinSets.jl
test/categorical_algebra/FreeDiagrams.jl

This PR implements
- the universal property for (co)limits of arbitrary free diagrams of FinSets
- (co)limits of arbitrary free diagrams of C-sets
In a future PR, I will use this to implement composites of structured multicospans specified by UWDs.

(Co)limits of general free diagrams of C-sets

---

docs/make.jl
docs/src/apis/graphs.md
src/graphs/BasicGraphs.jl
src/graphs/PropertyGraphs.jl

API docs for Graphs module

---

src/categorical_algebra/CSets.jl
test/categorical_algebra/CSets.jl

I implemented functorial data migration between CSets which the functor represented by an object dictionary and a hom dictionary.

Pullback functorial data migration for C-sets

---

src/programs/RelationalPrograms.jl
test/programs/RelationalPrograms.jl

This PR extends the `@relation` macro with optional support for named ports. See the docstring and the unit tests for more info.
@bosonbaas, I hope this will be helpful for querying SQL databases. My own intended use case is conjunctive queries of ACSets (not yet implemented!).

Port names in `@relation` macro

---

src/graphs/BasicGraphs.jl
src/graphs/BipartiteGraphs.jl
src/graphs/Graphs.jl
test/graphs/BipartiteGraphs.jl
test/graphs/Graphs.jl

A bare-bones implementation that provides the schemas, types, and basic accessors and mutators. Resolves #300.

Bipartite graphs

---

benchmark/FinSets.jl
src/categorical_algebra/FinSets.jl
test/categorical_algebra/FinSets.jl

Implements multiway hash joins, extending the standard two-way case, and benchmarks three-way joins.

Multiway hash joins

---

src/categorical_algebra/ACSetViews.jl
src/categorical_algebra/CSetDataStructures.jl
src/categorical_algebra/CategoricalAlgebra.jl
test/categorical_algebra/ACSetViews.jl
test/categorical_algebra/CategoricalAlgebra.jl

I accidentally deleted the branch for the previous PR, #340, so this continues that PR. Also, this includes queries. Given that the ACSetView structure still needs review, I figure that it makes sense to have both the ACSetView structure and the queries on the same PR, because changes to one will probably necessitate changes in the other.

Querying ACSets

---

src/categorical_algebra/CSetDataStructures.jl

This is useful because `pretty_table` from PrettyTables.jl presents a ton of options that can't be set through `IOContext` parameters to `show`.

Expose function `pretty_tables` for ACSets

---

src/theories/Monoidal.jl

Thanks to @philzook58 for pointing this out.

Two missing axioms in theory of monoidal categories

---

docs/src/apis/categorical_algebra.md
docs/src/index.md
src/categorical_algebra/FreeDiagrams.jl

Just a few documentation changes.

DOC: add some documentation from answering Breiner questions.

---

src/categorical_algebra/CSets.jl
test/categorical_algebra/CSets.jl

As explained in the docs, the backtracking search algorithm implemented here is the standard one. Future work would draw on the CSP literature to develop more efficient heuristics. Nevertheless, this should already be much faster than the naive brute-force algorithm.
This PR should be useful for:
- computing exponentials of C-sets (#276)
- rewriting C-sets, specifically finding matches of rewrite rules
A future PR should add support for monic/epic/iso constraints on the components of the transformation.

Find homomorphisms of C-sets using backtracking search

---

benchmark/Graphs.jl
src/graphs/GraphGenerators.jl
src/graphs/Graphs.jl
test/categorical_algebra/ACSetViews.jl
test/categorical_algebra/CSets.jl
test/graphics/GraphvizGraphs.jl
test/graphs/GraphGenerators.jl
test/graphs/Graphs.jl
test/wiring_diagrams/Algebras.jl
test/wiring_diagrams/CPortGraphs.jl

This covers some of the most common families for simple tests. Resolves #399.

Constructors for common families of graphs

---

src/theories/Category.jl

Reference: https://arxiv.org/abs/1705.04296

Generalized algebraic theory for displayed categories

---

src/categorical_algebra/CSets.jl
src/wiring_diagrams/Directed.jl
test/categorical_algebra/CSets.jl
test/graphics/YFilesWiringDiagrams.jl
test/wiring_diagrams/Algorithms.jl
test/wiring_diagrams/MonoidalDirected.jl

Sequel to #401 and #398. Resolves #57.

Convenience functions for homomorphism and isomorphism testing

---

src/categorical_algebra/CSets.jl

Besides cleaning up the control flow, this will be useful for doing things like counting homomorphisms or isomorphisms without making extra allocations.

Finer control over termination of morphism backtracking search

---

src/core/Syntax.jl
src/theories/Category.jl
src/theories/HigherCategory.jl
src/theories/Theories.jl
test/theories/Category.jl
test/theories/Monoidal.jl
test/theories/MonoidalAdditive.jl
test/theories/Theories.jl

Default syntax systems and pretty-printing for (co)presheaves

---

src/linear_algebra/GLA.jl
src/theories/MonoidalAdditive.jl

See the [nLab](https://ncatlab.org/nlab/show/additive+category) for the definition. Factored out of the GLA theory since it is generally useful.

Theory of additive categories

---

src/theories/Monoidal.jl

Typo in dagger axiom of hypergraph category

---

src/categorical_algebra/FinSets.jl
test/wiring_diagrams/Algebras.jl

Fix special case of cartesian product in FinSet bipartite limits

---

src/categorical_algebra/CSets.jl
test/categorical_algebra/CSets.jl

Support initial data in C-set homomorphism search

---

.github/workflows/reviewchecklist.yml

Signed-off-by: Micah Halter <micah@balena.io>

BUILD: Remove dependency on comment-on-pr github action

---

src/categorical_algebra/DataMigration.jl
test/categorical_algebra/DataMigration.jl

FIX: resolve attribute error in Delta migration

---

src/categorical_algebra/CSets.jl
src/categorical_algebra/DPO.jl
test/categorical_algebra/CSets.jl

Function to create subobject of C-set

---

src/categorical_algebra/CSets.jl
src/categorical_algebra/FinSets.jl
src/categorical_algebra/Limits.jl
src/categorical_algebra/Sets.jl
src/core/GAT.jl
src/theories/Category.jl
src/theories/HigherCategory.jl
src/theories/Monoidal.jl
src/theories/MonoidalAdditive.jl
src/wiring_diagrams/Undirected.jl
test/categorical_algebra/CSets.jl
test/categorical_algebra/FinSets.jl
test/categorical_algebra/Sets.jl
test/core/GAT.jl

Resolves #449 in a generic way.

(Co)cartesian category instances from (co)products

---

docs/src/apis/categorical_algebra.md

Gave a brief overview at the beginning of the documentation for acsets, also linked to the paper.

More acset documentation

---

src/core/Present.jl

This is refactored out of the struct acsets branch.

Simplify implementation of @present macro

---

docs/literate/graphs/subgraphs.jl

This small PR slightly expands the vignette on subgraphs.

Explain subobject meets and joins as adjoints

---

docs/literate/sketches/meets.jl
docs/make.jl

This uses FreeDiagrams to represent labelled Hasse Diagrams. Shows some basic graph algorithms for preorders.

Documentation example of meets building on preorders

---

src/categorical_algebra/CSetDataStructures.jl
src/categorical_algebra/CatElements.jl
test/categorical_algebra/CatElements.jl

I forgot to rebase before merging #431.

Update category of elements for struct acsets

---

docs/literate/sketches/meets.jl

FIX: #497 typo in meet description

---

src/categorical_algebra/CSets.jl
src/categorical_algebra/FinSets.jl
src/categorical_algebra/FreeDiagrams.jl
src/categorical_algebra/Limits.jl
test/categorical_algebra/FreeDiagrams.jl

I anticipate having more types that can play the role of diagrams soon.

Replace abstract base type for free diagrams with generic interface

---

src/categorical_algebra/Diagrams.jl
src/categorical_algebra/FinCats.jl
test/categorical_algebra/Diagrams.jl

Along with #542, this simple PR closes #537.

Basic `show` methods for diagrams and diagram morphisms

---

src/categorical_algebra/CSets.jl
src/categorical_algebra/DataMigrations.jl
src/categorical_algebra/FinCats.jl
src/categorical_algebra/FinSets.jl
src/categorical_algebra/FreeDiagrams.jl
src/categorical_algebra/Limits.jl
test/categorical_algebra/DataMigrations.jl
test/categorical_algebra/FinCats.jl
test/categorical_algebra/FreeDiagrams.jl

Reduce general limits to limits of bipartite free diagrams

---

.github/workflows/codecov.yml
docs/literate/graphs/graphs.jl
docs/make.jl

replacement for #553 without being bad at git

Vignette for graphs as C-sets

---

docs/literate/wiring_diagrams/wd_cset.jl
docs/make.jl

This vignette shows the differences between DWDs UWDs and CPGs with their schemas and associated DSLs.

DOC: adding vignette for WDs as C-Sets

---

docs/literate/sketches/smc.jl

Add some more exposition and talk about SMC term trees.

DOC: Add content to SMC sketch

---

docs/src/apis/programs.md
src/categorical_algebra/CSetDataStructures.jl
src/categorical_algebra/Categories.jl
src/categorical_algebra/DataMigrations.jl
src/categorical_algebra/Diagrams.jl
src/categorical_algebra/FinCats.jl
src/programs/DiagrammaticPrograms.jl
src/theories/Schema.jl
test/categorical_algebra/Categories.jl
test/categorical_algebra/DataMigrations.jl
test/categorical_algebra/Diagrams.jl
test/programs/DiagrammaticPrograms.jl

Closes #550. This should be the last major PR in my current push on data migration. There are a few loose ends that will be resolved in subsequent smaller PRs.

Data migration using gluings of conjunctive queries

---

src/categorical_algebra/CSetDataStructures.jl
src/categorical_algebra/CSets.jl
src/categorical_algebra/DataMigrations.jl
src/categorical_algebra/Diagrams.jl
src/categorical_algebra/FinCats.jl
src/categorical_algebra/FinSets.jl
src/categorical_algebra/FreeDiagrams.jl
src/categorical_algebra/Limits.jl
src/categorical_algebra/Sets.jl
src/graphs/BasicGraphs.jl
src/programs/DiagrammaticPrograms.jl
test/categorical_algebra/DataMigrations.jl
test/categorical_algebra/FinSets.jl
test/categorical_algebra/Limits.jl
test/categorical_algebra/Sets.jl

Closes #568 and addresses the most essential aspects of #556.

Data migration with data attributes

---

docs/literate/graphs/graphs_label.jl
docs/make.jl

Example of putting C-Set labels on Graphs.

DOC: Labelled Graph example with (co)limits

---

src/categorical_algebra/Categories.jl
src/categorical_algebra/FinSets.jl
src/categorical_algebra/FreeDiagrams.jl
test/categorical_algebra/FinSets.jl

A step towards the sort of thing we'd need for "lacsets" (cc @olynch).

Colimits of finite sets with named elements

---

src/categorical_algebra/CSetDataStructures.jl

Docstrings not attached to acset types

---

src/categorical_algebra/CSets.jl
src/categorical_algebra/Categories.jl
src/categorical_algebra/DataMigrations.jl
src/categorical_algebra/FinCats.jl
src/categorical_algebra/FinSets.jl
src/graphics/GraphvizCategories.jl
src/programs/DiagrammaticPrograms.jl
test/categorical_algebra/Categories.jl
test/categorical_algebra/DataMigrations.jl
test/categorical_algebra/FinCats.jl
test/programs/DiagrammaticPrograms.jl

There is more that could be done but this is still an improvement over what we had before.

Refactor API for generator names in finitely presented categories

---

src/categorical_algebra/CSetDataStructures.jl
test/categorical_algebra/CSetDataStructures.jl

There were some quite severe bugs here. I'm not sure whether I got all of them but at least the tests are better now.

Fix bugs in removing acset parts when indices are present

---

src/categorical_algebra/GraphCategories.jl
test/graphs/GraphAlgorithms.jl

This fixes issue #634 , just had to switch from neighbors to all_neighbors
I added tests aswell

Fix connected_component_bfs #634

---

Project.toml
docs/literate/graphics/graphviz_graphs.jl
docs/literate/graphs/graphs.jl
docs/make.jl
src/graphics/GraphvizGraphs.jl
test/graphics/GraphvizGraphs.jl

graphviz visualization for ACSetTransformation between Graphs

---

src/categorical_algebra/CSets.jl
test/categorical_algebra/CSets.jl

Based on @kris-brown's #682, or at least the part of it concerning colimits. This stuff is a bit subtle but hopefully the fairly detailed docstrings explain adequately what is going on here.

Colimits of acsets with given type components

---

docs/literate/categorical_algebra/diagrams.jl
src/categorical_algebra/Diagrams.jl
src/graphics/GraphvizCategories.jl
src/programs/DiagrammaticPrograms.jl
test/categorical_algebra/Diagrams.jl
test/programs/DiagrammaticPrograms.jl

Building on #693 and working toward #578.

Literal values in `@free_diagram` and `@migration` macros

---

src/programs/DiagrammaticPrograms.jl

Parse diagram DSLs to ASTs at macro expansion time where possible

---

src/programs/DiagrammaticPrograms.jl

Error message references undefined variable

---

src/categorical_algebra/FinCats.jl

Minor documentation fix

---

src/categorical_algebra/Diagrams.jl
test/categorical_algebra/Diagrams.jl

Should have been adding during #694.

Missing `op` method for `Diagram{Any}`

---

src/wiring_diagrams/Algebras.jl

@epatters this should be merged ASAP and then a new release should be tagged, because the JuliaHub demo depends on it.

Keyword args for `oapply` to expose (co)limit

---

docs/literate/categorical_algebra/diagrams.jl

Tiny fix for a "typo" I've stumbled upon.

Remove duplicate line in docs

---

src/graphs/Searching.jl
test/graphs/GraphAlgorithms.jl

Fix bug in `tree`

---

src/categorical_algebra/CSets.jl

Restore type parameters of acset transformations 

---

test/acsets/CSetDataStructures.jl
test/categorical_algebra/CSets.jl
test/categorical_algebra/DataMigrations.jl
test/categorical_algebra/FinCats.jl
test/categorical_algebra/StructuredCospans.jl
test/graphics/GraphvizGraphs.jl
test/graphs/BasicGraphs.jl

Clean up 32-bit support in tests

---

src/categorical_algebra/FinSets.jl
test/categorical_algebra/FinSets.jl

Fix method replacement in `FinDomFunction` constructor

---

.github/workflows/reviewchecklist.yml

I'm pretty sure this is correct, sadly I have no way of testing this before it gets merged to `master` 😅

Add check if review checklist has already been commented

---

src/categorical_algebra/CSets.jl

Remove acset transformation type parameters kept for backward compatibility

---

Project.toml
benchmark/Graphs.jl
experiments/TensorNetworks/src/TensorNetworks.jl
src/categorical_algebra/CSets.jl
src/categorical_algebra/FreeDiagrams.jl
src/categorical_algebra/Limits.jl
src/programs/RelationalPrograms.jl
src/wiring_diagrams/Algebras.jl
src/wiring_diagrams/Expressions.jl

Taking into account the breaking change in https://github.com/AlgebraicJulia/ACSets.jl/pull/31.

Upgrade to ACSets.jl v0.2

---

src/wiring_diagrams/Algebras.jl

Fix bug with uninitialized data in `oapply` for multispans

---

src/categorical_algebra/CSets.jl
src/categorical_algebra/FinCats.jl
test/categorical_algebra/CSets.jl
test/categorical_algebra/FinCats.jl

Trying to solidify the API before committing to it in a release.

Clean up API for functorality and naturality testing

---

.github/workflows/experiments.yml
.github/workflows/julia_ci.yml
README.md
docs/make.jl
docs/src/devdocs/style.md

After this gets merged we simply need to do the following:
1. Update default branch `master` to `main` with renaming
2. Make sure branch protection rule name gets updated (should be handled automatically)

Migrate from `master` branch to `main` branch

---

.github/workflows/reviewchecklist.yml

Debugged and validated solution on my own fork: https://github.com/mehalter/Catlab.jl/pull/1

BUILD: actually fix review checklist

---

Project.toml
src/categorical_algebra/CSets.jl
src/categorical_algebra/FinSets.jl
test/categorical_algebra/CSets.jl

Biheyting logic for acsets with variables

Subobject with attribute variables

---

src/theories/IndexedCategory.jl

This is technically a breaking change but I'm pretty confident nobody is using this stuff yet.

More GATs related to (op)indexed monoidal categories

---

docs/src/apis/categorical_algebra.md
docs/src/apis/graphs.md
src/graphics/GraphvizCategories.jl
src/graphics/GraphvizGraphs.jl
src/graphs/NamedGraphs.jl
test/graphics/GraphvizGraphs.jl
test/graphs/NamedGraphs.jl

Use named graphs API in Graphviz visualization

---

src/graphs/GraphAlgorithms.jl
src/graphs/GraphSearching.jl

Address #897, a super tiny PR, but this came up recently.

Fix types in graph algorithms

---

Project.toml

See https://github.com/AlgebraicJulia/ACSets.jl/pull/130 and #901.

Bump dependency on ACSets.jl

---

src/categorical_algebra/FunctorialDataMigrations.jl

See https://github.com/AlgebraicJulia/Catlab.jl/issues/903

Delete extraneous SigmaMigration method

---

src/wiring_diagrams/Algebras.jl
test/wiring_diagrams/Algebras.jl

Addresses #913, happy for comments.

Fix for queries with attributes using union types

---

src/categorical_algebra/CSets.jl
test/categorical_algebra/HomSearch.jl

Fixes for Julia v1.11

---

src/wiring_diagrams/Algebras.jl
src/wiring_diagrams/CPortGraphs.jl
src/wiring_diagrams/Directed.jl
src/wiring_diagrams/Undirected.jl
test/wiring_diagrams/Algebras.jl
test/wiring_diagrams/CPortGraphs.jl
test/wiring_diagrams/Directed.jl

This PR adds callable methods to Wiring Diagrams

Calling a wiring diagram does an `oapply`
