AlgebraicJulia/Catlab.jl

src/algebra/Network.jl, src/algebra/Tree.jl, src/doctrines/Monoidal.jl, src/doctrines/Relations.jl, src/wiring_diagrams/Core.jl, src/wiring_diagrams/Layers.jl, src/wiring_diagrams/WiringDiagrams.jl, test/Doctrines.jl, test/algebra/Network.jl, test/wiring_diagrams/Core.jl, test/wiring_diagrams/Layers.jl, test/wiring_diagrams/WiringDiagrams.jl
From the code documentation:
> This module defines a generic data structure to represent a wiring between one
layer of input ports and another layer of output ports. A wiring layer forms a
bipartite graph with independent edge sets the input ports and the output ports.
>
> Unlike wiring diagrams, wiring layers are an auxillary data structure. They are
not terribly interesting in their own right, but they are a useful intermediate
representation in some circumstances. For example, a morphism expression
comprised of generators, compositions, products, and wiring layers is
intermediate between a pure GAT expression (which has no wiring layers, but may
have identities, braidings, copies, etc.) and a wiring diagram, which is purely
graphical.
As part of this PR, I had hoped to implement an …
=> Data structure for wiring between layers of boxes

src/doctrines/Doctrines.jl, src/doctrines/Monoidal.jl, src/doctrines/Permutations.jl, src/wiring_diagrams/Expressions.jl, test/doctrines/Doctrines.jl, test/doctrines/Permutations.jl, test/wiring_diagrams/Expressions.jl
In conjunction with previous PR #35, we can now convert wiring diagrams to morphism expressions in a symmetric monoidal category. The expressions are not simplified, but it's a start.
=> Convert permutations to composities of braidings and identities

src/wiring_diagrams/Algorithms.jl, src/wiring_diagrams/Core.jl, src/wiring_diagrams/Expressions.jl, src/wiring_diagrams/GraphML.jl, src/wiring_diagrams/JSON.jl, test/programs/JuliaPrograms.jl, test/wiring_diagrams/Algorithms.jl, test/wiring_diagrams/Core.jl
Resolves #39 and #55 by reimplementing `substitute!` (now non-mutating and called `substitute`) and `encapsulate!` (now non-mutating and called `encapsulate`). Also exposes `encapsulated_subdiagram` as an exported function and adds `induced_subdiagram` as a non-mutating alternative to `rem_boxes!`.
=> Reimplement substitution and encapsulation of wiring diagrams to preserve box order

docs/literate/graphics/composejl_wiring_diagrams.jl, docs/src/apis/wiring_diagrams.md, src/graphics/ComposeWiringDiagrams.jl, src/graphics/TikZWiringDiagrams.jl, src/graphics/WiringDiagramLayouts.jl, src/wiring_diagrams/Algebraic.jl, src/wiring_diagrams/Algorithms.jl, src/wiring_diagrams/Core.jl, src/wiring_diagrams/Expressions.jl, src/wiring_diagrams/Layers.jl, src/wiring_diagrams/WiringDiagrams.jl, test/wiring_diagrams/Algebraic.jl, test/wiring_diagrams/Algorithms.jl, test/wiring_diagrams/Core.jl, test/wiring_diagrams/WiringDiagrams.jl
The units and counits are represented using junction nodes. Unlike the cases of diagonals or codiagonals, an implicit representation using only wires is not possible because it would require wires into output ports and wires out of input ports, breaking the important assumption for directed wiring diagrams that wires go from output ports to input ports.
=> Wiring diagrams for self-dual compact closed categories

docs/literate/graphics/tikz_wiring_diagrams.jl, docs/literate/programs/algebraic_nets.jl, src/graphics/ComposeWiringDiagrams.jl, src/graphics/TikZ.jl, src/graphics/TikZWiringDiagrams.jl, src/graphics/WiringDiagramLayouts.jl, src/programs/AlgebraicNets.jl, test/graphics/GraphvizWiringDiagrams.jl, test/graphics/TikZ.jl, test/graphics/TikZWiringDiagrams.jl
Part 2 of #46 and follow-up to #66. A few features are missing and will be documented in the issues.
=> Rewrite TikZ wiring diagrams to use backend-agnostic layout

src/core/Syntax.jl, src/graphics/WiringDiagramLayouts.jl, src/programs/JuliaPrograms.jl, src/wiring_diagrams/Algebraic.jl, src/wiring_diagrams/Core.jl, src/wiring_diagrams/Expressions.jl, src/wiring_diagrams/Serialization.jl, test/graphics/GraphvizWiringDiagrams.jl, test/wiring_diagrams/Algebraic.jl, test/wiring_diagrams/Algorithms.jl, test/wiring_diagrams/Core.jl, test/wiring_diagrams/Expressions.jl, test/wiring_diagrams/GraphML.jl, test/wiring_diagrams/JSON.jl
Addresses #74. The types `Ports` and `WiringDiagram` now take a type parameter. For example, we would write `WiringDiagram{CartesianCategory.Hom}` for wiring diagrams representing morphisms in a cartesian monoidal category. The type `WiringDiagram{Any}` behaves exactly as before, so there should be few breaking changes.
This PR also takes the opportunity to refactor the unit tests for wiring diagrams, eliminating uses of GAT expressions except where necessary.
Future PRs will improve support for specific doctrines, such as dagger categories, compact closed categories, and bicategories of relations.
=> Type-parametrized wiring diagrams

docs/literate/graphics/composejl_wiring_diagrams.jl, docs/literate/graphics/tikz_wiring_diagrams.jl, src/core/Rewrite.jl, src/core/Syntax.jl, src/doctrines/Monoidal.jl, src/doctrines/Relations.jl, src/graphics/ComposeWiringDiagrams.jl, src/graphics/GraphvizWiringDiagrams.jl, src/graphics/TikZWiringDiagrams.jl, src/graphics/WiringDiagramLayouts.jl, src/wiring_diagrams/Algebraic.jl, src/wiring_diagrams/Expressions.jl, test/doctrines/Monoidal.jl, test/wiring_diagrams/Algebraic.jl
Sequel to #68. Adds support for wiring diagrams for dagger symmetric monoidal categories, compact closed categories (not necessarily self-dual), dagger compact categories, and bicategories of relations.
Warning: Converting from GAT expressions to these wiring diagrams should work, but going in the other direction does not yet work. This will require a bit more effort.
=> Wiring diagrams for dagger categories and compact closed categories

docs/literate/graphics/graphviz_wiring_diagrams.jl, src/doctrines/Monoidal.jl, src/wiring_diagrams/Algebraic.jl, test/doctrines/Monoidal.jl, test/wiring_diagrams/Algebraic.jl
Resolves #95.
One neat feature of the wiring diagram representation is that the [axioms for a traced monoidal category](https://ncatlab.org/nlab/show/traced+monoidal+category) are automatically satisfied, as verified in the unit tests. For a graphical interpretation of the axioms, see Table 3 in [Selinger's 1999 paper](https://pdfs.semanticscholar.org/11bc/3ff959f1b6b473400ff8edc5763cfcef5926.pdf).
=> Doctrine and wiring diagrams for traced monoidal categories

src/core/GAT.jl, src/doctrines/Category.jl
Added some basic axiom saving support, and added support to use `where` instead of `<=` in `@signature`
=> Add equivalency axioms and "where" syntax to signature macro

docs/src/apis/core.md, src/core/GAT.jl, src/doctrines/Category.jl, src/doctrines/Monoidal.jl, src/doctrines/Relations.jl, test/core/GAT.jl, test/core/Syntax.jl
All tests still pass when running `Pkg.test("Catlab")`
=> Updated standard library, tests, and documentation to adopt the new where clause notation

src/core/GAT.jl, src/doctrines/Category.jl, src/doctrines/Monoidal.jl, src/experimental/Markov.jl, test/core/GAT.jl
Alias functions now fully respect inheritance and are correctly typed.
=> Fixed the generation of alias functions

docs/src/apis/core.md, src/core/GAT.jl, src/doctrines/AdditiveMonoidal.jl, src/doctrines/Category.jl, src/doctrines/Monoidal.jl, src/experimental/Markov.jl, src/linear_algebra/GLA.jl, src/linear_algebra/StructuredGLA.jl, test/core/GAT.jl
Added a second notation for `@op` macro inside of the `@theory`
```
@op begin
Hom :→
compose :⋅
end
```
Also updated tests to make sure both notations work, and found a typo/bug in one of the ParseError definitions
=> Added ability to define operation aliases in block form

src/graphics/ComposeWiringDiagrams.jl, src/graphics/TikZWiringDiagrams.jl, src/graphics/WiringDiagramLayouts.jl
Also, makes a start toward a triangle shape for TikZ diagrams, but there are some issues with triangles, notably that orientation is not yet accounted for and rounded corners don't work well, because TikZ is too dumb to factor the rounding into node anchors.
=> Ellipse shape for Compose.jl and TikZ wiring diagrams

docs/literate/graphics/composejl_wiring_diagrams.jl, docs/literate/graphics/tikz_wiring_diagrams.jl, src/graphics/TikZWiringDiagrams.jl, src/graphics/WiringDiagramLayouts.jl
This was possible before through method overloading, but sometimes that is overkill.
=> Customize shapes and styles of boxes in Compose/TikZ wiring diagrams

src/categorical_algebra/CategoricalAlgebra.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/ShapeDiagrams.jl, test/categorical_algebra/CategoricalAlgebra.jl, test/categorical_algebra/FinSets.jl, test/categorical_algebra/ShapeDiagrams.jl
Also includes a basic implementations of the category FinOrd, the skeleton of FinSet. Inspired by [existing code](https://github.com/jpfairbanks/SemanticModels.jl/blob/f772bef38bb5958ceed8051a07e41e53fece2eb3/src/CategoryTheory.jl) in SemanticModels.jl.
=> Computing pushouts of spans in FinOrd

src/categorical_algebra/FinSets.jl, test/categorical_algebra/FinSets.jl
Implements binary products, equalizers, and pullbacks in FinOrd. Sequel to #169.
=> Binary limits in FinOrd

experiments/Markov/src/MarkovCategories.jl, experiments/Markov/test/MarkovCategories.jl, src/core/GAT.jl, src/core/Rewrite.jl, src/core/Syntax.jl, src/programs/ParseJuliaPrograms.jl, src/wiring_diagrams/Algebraic.jl, src/wiring_diagrams/Expressions.jl, test/core/GAT.jl, test/core/Syntax.jl, test/programs/ParseJuliaPrograms.jl, test/wiring_diagrams/Algebraic.jl
Some first steps towards refactoring the GAT system (see #165):
- The `Typeclass` wrapper struct, a holdover from the days when GATs mixed with Julia code, has been removed.
- The `@theory`/`@signature` macros no longer generate a whole module with stub Julia types. Instead, they generate a single abstract type representing the theory, e.g. an abstract type `Category`. The theory of categories can then be retrieved by calling `theory(Category)`. So we are now abusing the module system somewhat less.
- The stub methods generated by `@theory`/`@signature` have been replaced with a mere generic function declaration, reducing the size of the method tables for `compose`, `id`, etc by about a half. (I don't know why I didn't do this before. Probably because when I first wrote that code I barely …
=> Begin refactoring of GATs

src/core/Present.jl, src/programs/ParseJuliaPrograms.jl, test/core/Present.jl, test/programs/ParseJuliaPrograms.jl
Clean up to the presentation system, enabled by #175:
- Type parameterize presentations by theory, so that a presentation of a category will have type `Presentation{Category}`. This fixes a longstanding known issue.
- Index generators by GAT type, so that, for example, it is fast to retrieve all the object generators, or all the morphism generators, in a presentation of a category.
=> Proper typing of presentations

src/categorical_algebra/FinRelations.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/Matrices.jl, src/theories/MonoidalMultiple.jl, src/theories/Relations.jl, test/categorical_algebra/CategoricalAlgebra.jl, test/categorical_algebra/FinRelations.jl, test/categorical_algebra/FinSets.jl
- Adds a GAT for distributive bicategories of relations
- As an instance, implements the category `FinOrdRel` of finite ordinals and binary relations
- Fixes an issue with type parameter explosion in `FinOrd`
Similarly to the existing type `FinOrdFunction`, the abstract type `FinOrdRelation` has concrete subtypes where the relation is represented implicitly by a boolean-valued Julia function or explicitly by a boolean matrix, where the latter case uses #178.
=> The distributive bicategory of relations FinOrdRel

docs/src/apis/wiring_diagrams.md, src/categorical_algebra/CSets.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/Graphs.jl, src/programs/ParseJuliaPrograms.jl, src/wiring_diagrams/Algebraic.jl, src/wiring_diagrams/Algorithms.jl, src/wiring_diagrams/Directed.jl, src/wiring_diagrams/Expressions.jl, src/wiring_diagrams/GraphML.jl, src/wiring_diagrams/JSON.jl, src/wiring_diagrams/Serialization.jl, src/wiring_diagrams/Undirected.jl, src/wiring_diagrams/WiringDiagrams.jl, test/categorical_algebra/CSets.jl, test/graphics/GraphvizWiringDiagrams.jl, test/wiring_diagrams/Algorithms.jl, test/wiring_diagrams/Directed.jl, test/wiring_diagrams/GraphML.jl, test/wiring_diagrams/JSON.jl, test/wiring_diagrams/Undirected.jl, test/wiring_diagrams/WiringDiagrams.jl
This PR is a first cut at undirected wiring diagrams, implementing:
- data structures for typed and untyped wiring diagrams, based on C-sets
- the operad structure, namely functions for full and partial operadic composition, based on pushouts in `FinOrd`
The PR is interspersed with various tweaks and improvements to C-sets. The most notable is a function `copy_parts!` that allows a sub-C-set of one C-set to be copied into another.
Next on the list for UWDs is basic support for visualization, probably starting with Graphviz.
=> Undirected wiring diagrams

src/categorical_algebra/FinRelations.jl, src/categorical_algebra/FinSets.jl
Renames the concrete subtypes of `FinOrdFunction` to `FinOrdFunc` and `FinOrdVector` and the subtypes of `FinOrdRelation` to `FinOrdPredicate` and `FinOrdMatrix`. If you've been using the abstract type constructors, like in the unit tests, nothing will break.
Resolves #184.
=> Rename concrete types for FinOrd and FinOrdRel

src/categorical_algebra/CSets.jl, src/categorical_algebra/Graphs.jl, test/categorical_algebra/CSets.jl
The bare minimum fix for #199. It does *not* add support for rolling back C-set "transactions" but it does at least ensure that the internal state is consistent. For now, this is all I plan to do about this problem.
```julia
julia> using Catlab.CategoricalAlgebra.Graphs
julia> g = Graph();
julia> add_vertices!(g, 3)
1:3
julia> add_edge!(g, 1, 4)
ERROR: AssertionError: 0 <= subpart <= cset.nparts.V
[SNIP]
julia> src(g)
1-element Array{Int64,1}:
1
julia> tgt(g)
1-element Array{Int64,1}:
0
```
=> Bounds check before assigning C-set subpart

docs/literate/graphics/graphviz_wiring_diagrams.jl, src/categorical_algebra/Graphs.jl, src/graphics/Graphviz.jl, src/graphics/GraphvizWiringDiagrams.jl, test/categorical_algebra/Graphs.jl, test/graphics/GraphvizWiringDiagrams.jl
The outer ports are represented as dangling wires, which are not fixed to an outer boundary. The drawings are therefore rudimentary, but this feature should serve as a quick-and-dirty way to visualize undirected wiring diagrams until we develop better methods.
=> Drawing undirected wiring diagrams with Graphviz

src/categorical_algebra/FinRelations.jl, src/categorical_algebra/FinSets.jl, src/wiring_diagrams/Undirected.jl, test/categorical_algebra/FinRelations.jl, test/categorical_algebra/FinSets.jl
Resolves #215 and follows up #184/#197. In summary:
- `FinOrd` and `FinOrdFunction` are renamed to `FinSet` and `FinFunction`
- `FinOrdRelOb` and `FinOrdRelation` are renamed to `FinRel` and `FinRelation`
- The abstract type `FinFunction` has concrete subtypes `FinFunctionCallable` and `FinFunctionVector` and `FinRelation` has subtypes `FinRelationCallable` and `FinRelationMatrix`. The concrete types are exported but should rarely be needed in user code, which can use the constructors for `FinFunction` and `FinRelation`
- Type parameters are used to distinguished the usual categories from their skeleta. So, `FinSet{Int}` is the skeleton of **FinSet** and `FinSet{<:AbstractSet}` is **FinSet**. Currently, only the former is implemented but the latter could be straightforwardly implemented …
=> Use standard names for FinSet and FinRel

docs/src/apis/wiring_diagrams.md, src/categorical_algebra/CSets.jl, src/theories/Monoidal.jl, src/theories/MonoidalAdditive.jl, src/theories/Relations.jl, src/wiring_diagrams/Algebraic.jl, src/wiring_diagrams/Directed.jl, src/wiring_diagrams/Expressions.jl, src/wiring_diagrams/MonoidalDirected.jl, src/wiring_diagrams/MonoidalUndirected.jl, src/wiring_diagrams/Undirected.jl, src/wiring_diagrams/WiringDiagrams.jl, test/categorical_algebra/CSets.jl, test/wiring_diagrams/Directed.jl, test/wiring_diagrams/MonoidalDirected.jl, test/wiring_diagrams/MonoidalUndirected.jl, test/wiring_diagrams/Undirected.jl, test/wiring_diagrams/WiringDiagrams.jl
Resolves #216 and goes most of the way toward #218:
- Adds constructors `junction_diagram` and `cospan_diagram` for UWDs with zero or one boxes
- Implements UWDs as a cospan algebra (see Fong & Spivak, 2019, "Hypergraph categories")
- Uses the foregoing to implement UWDs as a hypergraph category (properly speaking, UWDs whose outer ports have been partitioned into domain and codomain)
=> Undirected wiring diagrams as a hypergraph category

docs/src/apis/core.md, experiments/CompAlgebra/src/AlgebraicNets.jl, experiments/CompAlgebra/src/MathFormulas.jl, experiments/Markov/src/MarkovCategories.jl, src/categorical_algebra/FinRelations.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/Matrices.jl, src/categorical_algebra/PredicatedSets.jl, src/core/GAT.jl, src/core/Syntax.jl, src/linear_algebra/GLA.jl, src/linear_algebra/LinearMapsExternal.jl, src/linear_algebra/LinearOperatorsExternal.jl, src/linear_algebra/StructuredGLA.jl, src/theories/Category.jl, src/theories/Limits.jl, src/theories/Monoidal.jl, src/theories/MonoidalAdditive.jl, src/theories/MonoidalMultiple.jl, src/theories/Preorders.jl, src/theories/Relations.jl, src/wiring_diagrams/MonoidalDirected.jl, src/wiring_diagrams/MonoidalUndirected.jl, test/core/GAT.jl, test/core/Syntax.jl
I have implemented the change in the GAT parsing, and also converted a couple theories to the new syntax (right now, both syntaxes are supported). I can go convert the other theories, but I thought I'd get some feedback first.
=> More conventional Julia syntax for GAT extension

src/core/GAT.jl, src/core/Syntax.jl
The deprecation warning on the old syntax errors when run; this fixes the error.
=> BUG: _file=missing causes error in @warn

.github/workflows/TagBot.yml
According to the Documenter.jl docs
https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions 
This should allow the TagBot to build the documentation for tags and therefore for the stable versions. This should close #241.
=> Allow TagBot to build documentation

docs/make.jl
Not sure why TikzPictures broke on GitHub CI all of a sudden—probably due to a change in the Ubuntu distro building the docs—but hopefully this fixes it.
=> Work around old LaTeX distribution in GitHub CI

Project.toml
Pre v0.7 Compose is not compatible with Julia 1.0+ and its giving me issues with my package version resolving.
=> Added more restrictive compose dependency

Project.toml, docs/make.jl
Version bump the master branch. Currently if you depend on Catlab v0.7.4+ and `]dev Catlab` you get a version issue.
=> V0.7.4 Version Bump on Master

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
The tests were lost in the C-sets refactor (#219). I'm restoring them since they provide good coverage. This has exposed a few issues that should be resolved in follow-up PRs.
=> Restore original unit tests for C-sets

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
This fixes the bug where type checking is too strict when adding parts to a CSet
=> Improved type checking of add_parts

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
I think this commit should restore the intended behavior, which tries to strike a balance between allowing subtyping where useful and having an informative abstract type.
@mehalter, can you confirm that this fixes the problem you reported today?
=> Missing type parameters in abstract type for ACSets

src/categorical_algebra/CSetMorphisms.jl, src/categorical_algebra/CSets.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/FreeDiagrams.jl, src/categorical_algebra/Limits.jl, test/categorical_algebra/CSetMorphisms.jl, test/categorical_algebra/FreeDiagrams.jl, test/categorical_algebra/Limits.jl
Implements limits of C-sets without attributes, building on both #269 and #270. The algorithm for colimits is dual, so implementing it will be a copy-paste. However, writing the tests will take longer, so I'll leave colimits for next time.
This PR also refactors the interface for (co)limits and universal properties to be consistent across all diagram shapes. As a result, any limit of C-sets can be reduced to a limit in FinSet in a simple and generic way.
=> Limits of C-sets

src/categorical_algebra/CSetMorphisms.jl, test/categorical_algebra/CSetMorphisms.jl
Sequel to #271. We now support all limits and colimits of C-sets with the caveats that:
- the universal properties are not yet implemented
- attributes are not yet supported
=> Colimits of C-sets

src/categorical_algebra/CSetMorphisms.jl, test/categorical_algebra/CSetMorphisms.jl
Extends #273 with support for attributes. Note that this applies only to colimits, not limits.
That attributed C-sets have colimits derived from C-sets is similar to the fact that slice categories inherit colimits from the original category (see [the nLab](https://ncatlab.org/nlab/show/over+category#LimitsAndColimits)).
=> Colimits of attributed C-sets

src/wiring_diagrams/Directed.jl, src/wiring_diagrams/Undirected.jl
Implements a general `substitute` function for UWDs, like we already have for directed WDs. The two forms of `ocompose` for UWDs, which previously had disjoint implementations, are now special cases of `substitute`.
=> General substitution of undirected wiring diagrams

src/categorical_algebra/CSets.jl
Using `DataType` instead of `Type` prevents `UnionAll`s from being used as attribute types, which should be allowed. In Julia you rarely want to restrict to `DataType`.
=> Don't restrict to `DataType` in C-set attributes

src/categorical_algebra/CSetMorphisms.jl, src/categorical_algebra/CSets.jl, src/categorical_algebra/CategoricalAlgebra.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/FreeDiagrams.jl, src/categorical_algebra/Limits.jl, src/categorical_algebra/StructuredCospans.jl, src/theories/Schema.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/CategoricalAlgebra.jl, test/categorical_algebra/FinSets.jl, test/categorical_algebra/FreeDiagrams.jl, test/categorical_algebra/Limits.jl, test/categorical_algebra/StructuredCospans.jl
This PR implements a generic interface for [structured cospans](https://ncatlab.org/nlab/show/structured+cospan) plus a concrete implementation for C-sets. The category structure is implemented for structured cospans, while the hypergraph category and symmetric monoidal double category structures are deferred to subsequent PRs.
Structured cospans of C-sets have three cases to handle:
1. No data attributes: Feet are FinSets and apex is C-set
2. Attributes present, but not on the boundary: Feet are FinSets and apex is attributed C-set
3. Attributes present, including at the boundary: Feet are attributed C'-sets and apex is attributed C-set, where C' has one object (for convenience, the cospan can still be specified in FinSet)
Each of the three cases is illustrated in the tests.
=> Structured cospans of attributed C-sets

src/categorical_algebra/CSetMorphisms.jl, src/categorical_algebra/FreeDiagrams.jl, src/categorical_algebra/Limits.jl, src/categorical_algebra/StructuredCospans.jl, test/categorical_algebra/CSetMorphisms.jl, test/categorical_algebra/StructuredCospans.jl
Finishes the initial implementation of structured cospans by implementing the hypergraph category structure, including monoidal products of cospans by taking coproducts in the underlying categories.
Also resolves #280.
=> Structured cospans as a hypergraph category

src/categorical_algebra/CategoricalAlgebra.jl, src/categorical_algebra/FreeDiagrams.jl, src/categorical_algebra/Squares.jl, src/core/GAT.jl, src/theories/Category.jl, src/theories/Theories.jl, test/categorical_algebra/CategoricalAlgebra.jl, test/categorical_algebra/FreeDiagrams.jl, test/categorical_algebra/Squares.jl, test/theories/Category.jl
The goal of this PR is to implement the double category of commutative squares over any category. Starting off with
- Ob, Hom1, Hom2, Cell for the 0,1,2 cells respectively
- Term constructors compose1, compose2 for the 2 types of 2-cell compositions
- Include 2 copies of the definition of category for the two types of 1-cells
I should harmonize naming with 2 categories signature of the theory of 2-categories https://github.com/AlgebraicJulia/Catlab.jl/blob/f218d45f6f85e113eede4247bf3d63fe63751b81/src/theories/Category.jl#L82
=> Double Category of Squares

src/categorical_algebra/CSetDataStructures.jl, src/categorical_algebra/StructuredCospans.jl, test/categorical_algebra/CSetDataStructures.jl
The function `copy_parts!` is generalized to allow copying from a C-set to a C'-set where C !=C'. By default, it copies all common parts and subparts. A helper function `copy_parts_only!, which copies only data attributes (not other subparts), is also exposed in the public API.
Resolves #285.
=> Copy parts between C-sets with different schemas

src/categorical_algebra/CSetDataStructures.jl, src/categorical_algebra/StructuredCospans.jl, src/wiring_diagrams/Undirected.jl
Instead of computing the pushout of junctions in FinSet, we compute the pushout in a category Attr-C-Set where C = {Junction}, which can also be interpreted as a slice category in Set over the product of all the attribute types.
This PR should resolve #288 in the simplest way possible given the machinery we currently possess.
=> Substitute UWDs with arbitrary data attributes on junctions

src/core/Present.jl, test/core/Present.jl
Now, instead of writing
```julia
@present TheoryGraph(FreeCategory) begin
V::Ob
E::Ob
src::Hom(E,V)
tgt::Hom(E,V)
end
```
you can also write
```julia
@present TheoryGraph(FreeCategory) begin
(V, E)::Ob
(src, tgt)::Hom(E,V)
end
```
This should improve the readability of large presentations with lots of objects.
=> Abbreviated presentation syntax for generators of same type

src/categorical_algebra/CSetDataStructures.jl, test/categorical_algebra/CSetDataStructures.jl
Resolves #196, the last major missing feature in the low-level interface for C-sets. Removal is implemented using the "pop and swap" strategy; see the docstring for more info.
=> Remove parts from C-sets

src/graphs/BasicGraphs.jl, test/graphs/BasicGraphs.jl
Sequel to #293. Implements `rem_vertex!`, `rem_vertices!`, `rem_edge!`, and `rem_edges!` for the four core graph types (graphs, symmetric graphs, reflexive graphs, and symmetric reflexive graphs), as well as for half-edge graphs.
This completes the implementation of the basic operations of the LightGraphs API.
=> Remove vertices and edges from graphs

src/categorical_algebra/CSetDataStructures.jl, src/categorical_algebra/CSets.jl, src/graphs/BasicGraphs.jl, src/wiring_diagrams/Undirected.jl, test/categorical_algebra/CSetDataStructures.jl
Also adds a convenience accessor `parts` and improves an error message. Closes #299.
=> Indexing notation for C-sets

docs/Project.toml
Upgrade to latest version of Documenter to get https://github.com/JuliaDocs/Documenter.jl/pull/1440. Closes #247.
=> Upgrade Documenter to fix slow build times

src/categorical_algebra/StructuredCospans.jl, src/wiring_diagrams/Algebras.jl, src/wiring_diagrams/WiringDiagrams.jl, test/categorical_algebra/StructuredCospans.jl, test/wiring_diagrams/Algebras.jl, test/wiring_diagrams/WiringDiagrams.jl
Sequel to #315 that realizes structured multicospans as an algebra of the operad of undirected wiring diagrams. This is the fully unbiased alternative to structured cospans as a hypergraph category.
A bit more testing is needed, but with the right machinery in place this is surprisingly easily to implement: just set up the appropriate diagram and compute its colimit!
@mehalter, this should replace the whole pipeline of `@program` -> `to_hom_expr` -> `functor`.
=> The UWD algebra of structured multicospans

src/theories/DoubleCategory.jl, test/theories/DoubleCategory.jl
The treatment of the braidings in symmetric monoidal double categories is *not* symmetric with respect to the vertical and horizontal directions (see reference cited in docstring). This PR tries to fix it. I think the term constructors are now right. We're still missing some axioms across the double category GATS, but that's less important.
=> Fix braidings in symmetric monoidal double categories

src/categorical_algebra/FreeDiagrams.jl, src/categorical_algebra/StructuredCospans.jl, test/categorical_algebra/FreeDiagrams.jl, test/categorical_algebra/StructuredCospans.jl
Adds a function `bundle_legs` that combines the legs of multispans, multicospans, or structured multicospans using (co)products.
=> Bundle legs of structured multicospans

src/categorical_algebra/CSetDataStructures.jl, src/core/Syntax.jl, src/graphics/ComposeWiringDiagrams.jl, src/graphics/ConvexExternal.jl, src/graphics/WiringDiagramLayouts.jl
As described in #324, dispatching on `::Val{x}` is slower than dispatching on `::Type{Val{x}}` because, I assume, `Val(x)` causes an allocation while `Val{x}` doesn't. On my machine, this change gives a 20x speedup on the benchmark in #324.
@bosonbaas, can you compare on the original benchmark that prompted this issue?
=> Speed up dispatch on value types

.github/workflows/benchmarks.yml, benchmark/Graphs.jl, src/categorical_algebra/CSetDataStructures.jl, test/categorical_algebra/CSetDataStructures.jl
As a sequel to #334, this PR optimizes the basic getters and setters for C-sets (`subpart`, `incident`, `set_subpart(s)!`) by benchmarking the Graphs module against LightGraphs and MetaGraphs.
With these optimizations, the getters and setters can be used elementwise (i.e., in non-vectorized fashion) without loss of performance, at least when the subpart name is hard-coded as a symbolic literal. The main tricks are to `@inline` appropriately and pass types instead of symbols wherever possible. The goal is to ensure that names that *are* constant are treated as constant by the compiler.
In comparison with LightGraphs, we are only occasionally faster but rarely more than 10x slower, at least on this simple set of benchmarks. OTOH, we outperform MetaGraphs in every benchmark. This is …
=> Optimize getters and setters for C-sets

src/categorical_algebra/CSetDataStructures.jl, test/categorical_algebra/CSetDataStructures.jl
Right now this is very basic; I plan to add data validation and possibly new syntaxes later on. Currently,
``` julia
g = @acset Graph begin
V = 2
E = 2
src = [1,2]
tgt = [2,1]
end
```
works, but this will not successfully reject most ill-formed ACSets.
=> Convenient Macro for Creating ACSets

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
As follow-up to #317, the `migrate!` function can now be used like `copy_parts!`, although the latter is `@generated` and the former is not, among other differences.
=> Extend `migrate!` to attributed C-sets that are not empty

src/linear_algebra/LinearAlgebra.jl, src/linear_algebra/TensorNetworks.jl, src/programs/RelationalPrograms.jl, src/wiring_diagrams/Algebras.jl, src/wiring_diagrams/ScheduleUndirected.jl, test/linear_algebra/LinearAlgebra.jl, test/linear_algebra/TensorNetworks.jl, test/programs/RelationalPrograms.jl, test/wiring_diagrams/ScheduleUndirected.jl
This PR makes the interface for evaluating scheduled UWDs consistent with that for operad algebras. So now you can implement `oapply` once and use it for both one-shot evaluations and scheduled evaluations.
I also took the opportunity to refactor the accumulating functionality for tensor networks into its own submodule inside `Catlab.LinearAlgebra`. This makes official the operad algebra of tensors over a rig.
=> Consistent interface for UWD schedule evaluation

Project.toml, src/categorical_algebra/CSetDataStructures.jl, test/categorical_algebra/CSetDataStructures.jl
This PR:
- allows any column-based table type compliant with [Tables.jl](https://github.com/JuliaData/Tables.jl) to be used for the tables in a C-set
- switches the default table type to [TypedTables.jl](https://github.com/JuliaData/TypedTables.jl), which closes #330
The following concrete table types are known to work:
- StructArrays (the old default)
- TypedTables (the new default)
- named tuples of arrays (validated in the unit tests)
=> Support any Tables.jl-compliant backend for tables in C-set

src/categorical_algebra/FinSets.jl, src/categorical_algebra/FreeDiagrams.jl, src/categorical_algebra/Limits.jl, src/categorical_algebra/Sets.jl, test/categorical_algebra/FinSets.jl
This PR enables limits and colimits to be implemented by different algorithms, via an optional argument `alg`. To compute pullbacks of multicospans, an important primitive for joins on relational databases, we now support the algorithms:
- [Nested-loop join](https://en.wikipedia.org/wiki/Nested_loop_join): the naive algorithm, already implemented as the product-equalizer composite limit
- [Sort-merge join](https://en.wikipedia.org/wiki/Sort-merge_join): sorts the function values to allow a single pass through the data
A future PR will implement indexed `FinFunctions` and the [hash join](https://en.wikipedia.org/wiki/Hash_join) algorithm. We also need to add benchmarks comparing the different algorithms on different pullbacks.
As a followup to #347, this PR also adds support for equalizers …
=> Sort-merge algorithm for pullbacks

benchmark/FinSets.jl, benchmark/Graphs.jl, benchmark/README.md, benchmark/benchmarks.jl, src/categorical_algebra/FinSets.jl, test/categorical_algebra/FinSets.jl
This PR:
- Add types for `FinFunction`s and `FinDomFunction`s with indices, so that preimages can be efficiently computed
- Implements the hash join algorithm for binary pullbacks/two-way joins
- Adds benchmarks for three pullback/join algorithms we now support, namely nested loop joins, sort-merge joins, and hash joins
As expected by their asymptotic complexity, both the sort-merge join and hash join are *way* faster than the naive algorithm, the nested loop join. At least in these benchmarks, the hash join is generally a bit faster than the sort-merge join. Note that this includes the time for computing the indices; when used with the pre-indexed functions coming from C-sets, the performance of hash joins should be even better.
=> Indexed `FinFunction`s and hash joins

src/categorical_algebra/CSetDataStructures.jl, src/theories/Schema.jl, test/categorical_algebra/CSetDataStructures.jl
Pretty simple, basically:
``` julia
map(Int,s -> Int(s[1]),:Weight,g::WeightedGraph{String})::WeightedGraph{Int}
```
All attributes with a given codomain get converted using the supplied function. Partly addresses #335.
=> Haskell-style map function for ACSets

src/programs/RelationalPrograms.jl, test/programs/RelationalPrograms.jl
Supported for untyped UWDs, with either named or unnamed ports.
@mehalter, this generalizes #318.
=> Allow context to be left implicit in `@relation` macro

src/categorical_algebra/FinSets.jl, src/categorical_algebra/Sets.jl, src/wiring_diagrams/Algebras.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/FinSets.jl, test/categorical_algebra/Sets.jl, test/wiring_diagrams/Algebras.jl
Sequel to #358 that allows parameters to be set in conjunctive queries of ACSets. By "parameter" I mean a constant value assigned to a junction in the query diagram. Like the rest of the query functionality, this is handled through general machinery for limits of finite-domain functions.
=> Support for constants in conjunctive queries on ACSets

.github/workflows/CompatHelper.yml
Follow up to #367.
Reuses the Documenter SSH key as described in the CompatHelper docs.
=> Set up CompatHelper

src/graphics/GraphvizGraphs.jl, src/graphics/GraphvizWiringDiagrams.jl, src/graphics/WiringDiagramLayouts.jl, src/graphics/YFilesWiringDiagrams.jl, src/programs/ParseJuliaPrograms.jl, src/wiring_diagrams/Algorithms.jl, src/wiring_diagrams/Directed.jl, src/wiring_diagrams/Expressions.jl, src/wiring_diagrams/GraphML.jl, src/wiring_diagrams/JSON.jl, src/wiring_diagrams/MonoidalDirected.jl, test/wiring_diagrams/Directed.jl
Reimplements directed wiring diagrams to be C-sets for suitable schema C. The core imperative interface is unchanged but it's implementation is different.
=> Implement DWDs using ACSets, v2

src/categorical_algebra/ACSetViews.jl, src/categorical_algebra/CSetDataStructures.jl, src/categorical_algebra/CSets.jl, src/categorical_algebra/StructuredCospans.jl, src/theories/Schema.jl
=> No type piracy in ACSet schema description types

src/theories/Schema.jl
Thanks to @sjbreiner for reporting this bug. Resolves #394.
=> Typo in equational axioms of Schema

docs/make.jl
The Literate.jl docs require extra dependencies and take a long time to build, so it is sometimes useful to disable them. Usage:
```
julia --project=docs docs/make.jl --no-literate
```
Closes #396.
=> Command-line switch to disable Literate.jl docs

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
Sequel to #398. A simple modification to the backtracking search algorithm that maintains a partial inverse mapping.
=> Extend backtracking search to C-set monomorphisms and isomorphisms

src/theories/Category.jl
Adding GATs for coPresheaf and Presheaf, as left/right modules of a category.
They are both straightforward. There are possibly some small choices to finalize.
Can also extend both to profunctors, which I'm sure will be useful.
=> add theories of co/Presheaf

src/core/Present.jl
This feature is used [semanticflowgraph](https://github.com/IBM/semanticflowgraph).
The diff is one character.
=> Fix generators with no names in `@present` macro

benchmark/Graphs.jl
This makes it so that the LightGraphs benchmarks can be separated from the Catlab benchmarks when doing analysis of benchmark results.
=> Refactor benchmarks to separate Catlab/LightGraphs

src/theories/Monoidal.jl
This is a set-valued lax symmetric monoidal functor, viewed as an action of a SMC.
I'm not sure about the name, which seems to be nonstandard.
=> Theory of symmetric monoidal copresheaves

benchmark/Graphs.jl, src/categorical_algebra/CSets.jl, src/graphs/GraphGenerators.jl, src/wiring_diagrams/Algebras.jl, test/graphs/GraphGenerators.jl, test/wiring_diagrams/Algebras.jl
Benchmark counting triangles in a graph via
- C-set homomorphism search based on backtracking search
- conjunctive query using FinSet limits
The third commit gives a 10-20x speed improvement to the homomorphism search method.
Both methods are much slower than LightGraph's dedicated procedure for counting triangles. That is not surprising given the big difference in generality between the algorithms. Still, I think that large performance improvements are on the table, particularly for the CSP algorithm which I suspect is much slower than it should be.
=> Benchmark counting triangles in a graph

experiments/CompAlgebra/src/AlgebraicNets.jl, experiments/Markov/src/MarkovCategories.jl, src/theories/Category.jl, src/theories/HigherCategory.jl, src/theories/Monoidal.jl, src/theories/MonoidalAdditive.jl, src/theories/Preorders.jl, src/theories/Relations.jl, test/theories/Category.jl
This is a change that should have been made long ago: there is no good reason to normalize associativity but not unitality in the default syntax systems for categories.
=> Enforce unitality of composition in default syntax systems

.github/workflows/reviewchecklist.yml
The `yml` before this PR is completely valid. I think there is a bug in the Github Actions interpreter where it is getting confused. Hoping that this will fix things.
=> BUILD: Fix error in github actions interpreting |

.github/workflows/reviewchecklist.yml
This should fix the Review Checklist GitHub Action for remote fork pull requests. By changing the trigger from `pull_request` to `pull_request_target`, it should make the code from from the base branch instead of the branch that is being merged. The branch being merged, if it's a fork, does not have write permissions on the base repository and is there to keep secrets from being leaked.
NOTE: this will need to be merged into master before we can test it.
=> BUILD: Moved to pull_request_target trigger for review checklist

test/Project.toml
LinearOperators.jl v2 just came out, and a few of the GLA tests are failing on it. This PR, meant to be temporary, restricts to v1 until the GLA code is fixed.
=> Restrict to LinearOperators v1

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
For some applications, it is useful to restrict the monic constraint to just certain CSet components. This is implemented here by extra optional keyword arguments `isos` and `monics` which are vectors of symbols.
=> Homomorphism search, monic or iso on particular components

src/categorical_algebra/DataMigration.jl
See commit message for info. Follow-up to #433.
IMO, we should reconsider whether we want to be so liberal about attaching constructors to *all* acsets, but we can revisit that in a separate issue.
=> Tighten types on ACSet constructor for data migration

README.md, docs/src/index.md
In the README, it says that Catlab is not meant to be a graphical editor; I edited this to say that Catlab *is* the backend to a graphical editor, however!
=> Reference Semagrams in README

src/categorical_algebra/CSetDataStructures.jl, test/categorical_algebra/CSetDataStructures.jl
This works around an issue reported on the Zulip, but eventually we will want a more principled solution.
=> Don't vectorize `incident` when attribute is a tuple

src/graphics/GraphvizWiringDiagrams.jl, test/graphics/GraphvizWiringDiagrams.jl
Provides visualization tooling for CPortGraphs. An example of how a star CPortGraph is visualized is provided below.
```julia
to_graphviz(pg, edge_attrs=Dict(:len => "1.0"), port_labels=true, box_labels=true)
```
=> ENH: add function for visualizing CPortGraphs

src/categorical_algebra/CSetDataStructures.jl, test/categorical_algebra/CSetDataStructures.jl
=> @acset macro fix for runtime values

src/categorical_algebra/CSetDataStructures.jl, test/categorical_algebra/CSetDataStructures.jl
A side effect of #463 caused a test failure in AlgDynamics.
=> Restore support for non-vector iterators in `@acset` macro

src/categorical_algebra/CSets.jl, src/categorical_algebra/DPO.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/FreeDiagrams.jl, src/categorical_algebra/Limits.jl, test/categorical_algebra/DPO.jl, test/categorical_algebra/FinSets.jl, test/categorical_algebra/FreeDiagrams.jl
This PR
- defines a generic interface for pushout complements (`pushout_complement` and `can_pushout_complement`)
- extracts an implementation of pushout complements in FinSet from pushout complements in C-Set
- refactors the latter to use the former
=> Generic interface for pushout complements

benchmark/Graphs.jl, src/graphs/BasicGraphs.jl, src/graphs/BipartiteGraphs.jl, src/graphs/PropertyGraphs.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/StructuredCospans.jl
This PR fixes the overly loose typing of accessors like `vertices`, `edges`, and `src`. This is important for exporting a graphs interface that is generic over ACSet types. We will take advantage of this to fix longstanding hacks in CombinatorialSpaces.
This was made possible by the struct acsets refactor (#376).
=> Refactor type hierarchy in graphs module

src/categorical_algebra/CSets.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/Subobjects.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/DPO.jl, test/categorical_algebra/FinSets.jl
Closes #472. This is a cleaner design and will result in fewer allocations when stringing together sub-C-set operations.
=> Different internal representations of subobjects

docs/literate/sketches/meets.jl
I got meet and join backwards in the previous version. This version uses Meet = Greatest Lower Bound.
=> FIX: get meet/join right

src/categorical_algebra/ACSetInterface.jl
This caused some minor breakage in CombinatorialSpaces, and I think the old behavior makes more sense.
=> Restore pre-v0.13 behavior for indexing acsets with static arrays

src/graphics/GraphvizGraphs.jl
The conventions are now inline with `to_graphviz` functions for other graph types.
=> More flexible Graphviz support for acset schemas

.github/workflows/downstream.yml
This will help me determine whether borderline changes should be considered breaking. To avoid long check times, the action is only run when triggered manually.
=> GitHub action to test downstream packages

src/linear_algebra/TensorNetworks.jl, src/programs/RelationalPrograms.jl, src/wiring_diagrams/MonoidalUndirected.jl, src/wiring_diagrams/ScheduleUndirected.jl, src/wiring_diagrams/Undirected.jl, test/linear_algebra/TensorNetworks.jl, test/programs/RelationalPrograms.jl
Following of the approach of #486, this PR refactors the type hierarchy of undirected wiring diagrams.
=> Refactor type hierarchy for UWDs

Project.toml, benchmark/Graphs.jl, src/categorical_algebra/CSetDataStructures.jl, src/categorical_algebra/CSets.jl, src/wiring_diagrams/Algebras.jl, test/Project.toml, test/categorical_algebra/CSets.jl, test/wiring_diagrams/Algebras.jl
This PR allows the C-set homomorphism finding functions to have different algorithmic backends. In addition to backtracking search, which was already supported, the conjunctive query machinery can now be used to find homomorphisms. Thanks to @olynch for doing the [original implementation](https://github.com/AlgebraicJulia/CombinatorialChains.jl/blob/d1a54dea195d87879ac18b047964eb2df5ca12de/src/ConjuctionQueryHomomorphism.jl) of this feature. The implementation here also supports data attributes.
I also take the opportunity to remove the dependency on TypedTables, no longer needed after the struct acsets refactor. An *optional* dependency on DataFrames is added so that the `query` function can return a table when possible.
=> Find C-set homomorphisms using conjunctive queries

benchmark/FinSets.jl, docs/literate/sketches/meets.jl, docs/literate/sketches/partitions.jl, docs/src/apis/categorical_algebra.md, src/categorical_algebra/CategoricalAlgebra.jl, src/wiring_diagrams/Algebras.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/CatElements.jl, test/categorical_algebra/DPO.jl, test/categorical_algebra/FinSets.jl, test/categorical_algebra/FreeDiagrams.jl, test/categorical_algebra/StructuredCospans.jl, test/wiring_diagrams/Algebras.jl
Given their fundamental importance, reexporting these submodules from `CategoricalAlgebra` is something I should have done from the get-go but for some reason didn't.
=> Reexport the `Sets` and `FinSets` submodules

src/categorical_algebra/CSetDataStructures.jl, src/categorical_algebra/CSets.jl, src/categorical_algebra/Categories.jl, src/categorical_algebra/DataMigrations.jl, src/categorical_algebra/FinCats.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/FreeDiagrams.jl, src/categorical_algebra/Sets.jl, src/theories/Schema.jl, test/categorical_algebra/FinCats.jl, test/categorical_algebra/FinSets.jl, test/categorical_algebra/Sets.jl
Introduces a type `CompositeFunctor` for lazy compositions of functors and also refactors the lazy composition of functions in **Set** to use a new type `CompositeFunction`.
=> Composite functions and functors

src/categorical_algebra/Diagrams.jl, src/categorical_algebra/FinCats.jl, src/categorical_algebra/FinSets.jl, src/graphs/BasicGraphs.jl, src/programs/DiagrammaticPrograms.jl, test/categorical_algebra/DataMigrations.jl, test/categorical_algebra/Diagrams.jl, test/programs/DiagrammaticPrograms.jl
Previously the column name ended up being `1`, which was confusing.
=> Use meaningful column name when promoting trivial queries

src/categorical_algebra/DataMigrations.jl, test/categorical_algebra/DataMigrations.jl
I think these constructors are too general to apply to all acset types, especially the latter one that takes two dicts. Of course, anyone is free to add particular migration constructors to particular struct acset types, provided they own those types.
=> Deprecate data migration constructors for acsets

src/categorical_algebra/DataMigrations.jl, src/categorical_algebra/FinSets.jl, test/categorical_algebra/DataMigrations.jl, test/categorical_algebra/FinSets.jl
=> Use meaningful element type in tabular sets

src/categorical_algebra/CSetDataStructures.jl, src/categorical_algebra/CSets.jl, src/categorical_algebra/DataMigrations.jl, src/categorical_algebra/Diagrams.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/FreeDiagrams.jl, src/categorical_algebra/Limits.jl, test/categorical_algebra/DataMigrations.jl, test/categorical_algebra/FinSets.jl, test/categorical_algebra/FreeDiagrams.jl
By using and extending the limits system, this design clarifies the computations in conjunctive data migration and paves the way for an easy, perfectly dual implementation of agglomerative data migration (#541).
This PR also closes #547.
=> Better architecture for conjunctive data migration

src/categorical_algebra/DataMigrations.jl, src/categorical_algebra/Diagrams.jl, src/categorical_algebra/FinCats.jl, src/categorical_algebra/FinRelations.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/Limits.jl, src/programs/DiagrammaticPrograms.jl, test/categorical_algebra/DataMigrations.jl, test/categorical_algebra/FinSets.jl, test/programs/DiagrammaticPrograms.jl
The dual of conjunctive data migration. Closes #541.
=> Agglomerative data migration

src/graphics/Graphviz.jl, src/graphics/GraphvizWiringDiagrams.jl, test/graphics/Graphviz.jl
For visualizing a dynamic process (each timestep represented by a wiring diagram), I've found it's helpful to have a [title](https://stackoverflow.com/questions/6450765/how-do-you-center-a-title-for-a-diagram-output-to-svg-using-dot) that provides information during that timestep.  E.g.
To do this, I added a `Title` as a new kind of `Graphviz.Statement` and added a `title::Union{Nothing,String}` keyword argument to `to_graphviz`.
=> Allow adding titles to wiring diagrams

src/graphics/GraphvizWiringDiagrams.jl
This is one way we could allow users to color wiring diagrams. A dictionary mapping box IDs to strings (e.g. `"lightblue"`) can be passed to `to_graphviz`, with the default behavior being unchanged (unfilled boxes, black junctions).
=> Arbitrarily color boxes / junctions of a wiring diagram

src/core/Present.jl, src/programs/DiagrammaticPrograms.jl, test/categorical_algebra/DataMigrations.jl, test/programs/DiagrammaticPrograms.jl
Assorted, somewhat related features needed for our physics project:
- Support GAT expressions in `@finfunctor` and `@diagram` macros
- Allow unnamed/anonymous morphisms in indexing category
- New `@free_diagram` macro with alternative interpretation of equation syntax
=> GAT expressions and anonymous morphisms in `@diagram` macro

docs/src/apis/categorical_algebra.md
This PR adds the ACSetInterface file to the docs markdown so that the doscstrings in ACSetInterface.jl will build in the documentation.
=> DOC: add ACSetInterface to docs

src/categorical_algebra/DPO.jl
The current DPO interface does not allow users to access the intermediate morphisms involved in computing the rewrite. These can be important for applications that need to know how data in the original CSet relates to data in the rewritten CSet.
=> Expose DPO morphism relating input and output of rewriting

src/graphs/PropertyGraphs.jl
It's enough for the input acset to *have* a graph. It doesn't have to *be* a graph.
=> Loosen types for Graph to PropertyGraph constructors

docs/Project.toml, src/graphics/ConvexExternal.jl
The docs build has been failing lately because Convex.jl has been downgrading to v0.12, which is too old, yet when I upgrade to v0.14 (by downgrading other packages), I get a segfault. Luckily, v0.15 was just released this evening, which seems to resolve the issues.
=> Upgrade Convex.jl to v0.15

src/categorical_algebra/FinCats.jl, src/graphs/GraphAlgorithms.jl, src/graphs/PropertyGraphs.jl, test/categorical_algebra/FinCats.jl, test/graphs/GraphAlgorithms.jl
A property a FinFunctor may or may not have is being an initial functor (dual of [final functor](https://ncatlab.org/nlab/show/final+functor)). This can be straightforwardly computed for functors between free categories finitely presented by DAGs. For a functor of this sort F: S->T, we check whether, for each object t in Ob(T), that the comma category F/t is nonempty and connected.
This requires the path enumeration of DAGs.
=> Initiality test for FinFunctors

src/categorical_algebra/CatElements.jl, test/categorical_algebra/CatElements.jl
These are useful things to have when working with category of elements.
An error is thrown in in the inverse function if a graph tries to assign the same foreign key two different values.
=> Category of elements action on morphisms and inverse constructions

src/categorical_algebra/Diagrams.jl, test/categorical_algebra/Diagrams.jl
Diagrams/diagram homs do not use auto hash equals, so this must be defined manually.
=> add hash method for diagram/diagram hom

benchmark/Graphs.jl, benchmark/make_plots.jl, benchmark/plots.jl, src/categorical_algebra/ACSetInterface.jl, src/categorical_algebra/CSetDataStructures.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/GraphCategories.jl, src/graphs/BasicGraphs.jl, src/graphs/GraphAlgorithms.jl, src/graphs/GraphGenerators.jl, src/graphs/Graphs.jl, src/graphs/Searching.jl, test/graphs/BasicGraphs.jl, test/graphs/GraphGenerators.jl, test/graphs/Searching.jl
This contains updated benchmarks, along with code to generate figures for the paper. It also has a lot of miscellaneous optimizations; before this gets merged, I will look back and describe them.
=> Benchmarks for paper

src/categorical_algebra/CSets.jl, src/theories/Monoidal.jl, src/theories/MonoidalAdditive.jl
It's still feels a bit hacky to have to do this at all, but this PR is definitely an improvement over what we had before. The function `Base.typename` is available in recent versions of Julia.
=> Replace half-baked function `roottype` with `Base.typename`

src/categorical_algebra/CSets.jl, src/core/Present.jl, src/theories/Category.jl, test/core/Present.jl
This PR adds a GAT for [M-categories](https://ncatlab.org/nlab/show/M-category), a simple but underappreciated concept already used when distinguishing tight and loose acset transformations.
It has minor fixes/improvements to the `@present` macro encountered along the way.
=> GAT for M-categories

src/programs/DiagrammaticPrograms.jl, test/programs/DiagrammaticPrograms.jl
I held off on this feature when first implementing the diagram DSL, but I think its convenience outweighs the slightly awkward implementation.
=> Support expressions of form `f(x) == g(y)` in diagram DSL

src/categorical_algebra/CSetDataStructures.jl, test/categorical_algebra/CSetDataStructures.jl
A very bad bug that left unique indices for morphisms (not data attributes) almost completely broken. At least now we have some basic unit tests for this case.
=> Fix allocation of unique indices for morphisms in C-sets

src/categorical_algebra/CSetDataStructures.jl, src/categorical_algebra/CSets.jl, src/categorical_algebra/Categories.jl, src/categorical_algebra/DataMigrations.jl, src/categorical_algebra/Diagrams.jl, src/categorical_algebra/FinCats.jl, src/categorical_algebra/FreeDiagrams.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/Categories.jl, test/categorical_algebra/DataMigrations.jl, test/categorical_algebra/Diagrams.jl, test/categorical_algebra/FinCats.jl
This PR implements:
- Representable C-sets, subject to the limitations of our current implementation of left pushforward data migration
- The contravariant Yoneda embedding
- The oppositization 2-functor
- Various small fixes and improvements encountered along the way while using this stuff
=> Representables and the Yoneda embedding

docs/Project.toml
It was previously at v0.25, which is now quite outdated.
=> Bump Documenter to v0.27

src/categorical_algebra/DataMigrations.jl, test/categorical_algebra/DataMigrations.jl
In the future, we could compute this as a single left Kan extension rather than precomputing the Yoneda embedding and taking colimits of representables.
=> Colimits of representables for migration functors

src/categorical_algebra/DataMigrations.jl, test/categorical_algebra/DataMigrations.jl
This is a degenerate case of a conjunctive data migration.
=> Handle special case of pullback migration in `colimit_representables`

src/categorical_algebra/DataMigrations.jl, src/categorical_algebra/Diagrams.jl, src/categorical_algebra/FinCats.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/Limits.jl, test/categorical_algebra/DataMigrations.jl, test/programs/DiagrammaticPrograms.jl
A prime example of how the Julia compiler's inability to reliably infer types in the base case of an empty `map` leads to bugs and general frustration.
=> Fix type ambiguities with empty diagrams in data migration

src/categorical_algebra/CSets.jl
The type_components of LooseACSetTransformations can be given the wrong types due to a bug which mixes  `acodom_nums` and `attrtype_num`. This leads to a runtime error when one tries to call an incorrectly-typed function.
In CSets.jl line 334, `attrtype(S)` and `acodom_nums` shouldn't be zipped, as `acodom_nums` is for each attr, not each attrtype. The "i" we want is actually there is `attrtype_num(S,type)`
=> LooseAcsetTransformation type component coercion 

src/categorical_algebra/CSetDataStructures.jl, src/categorical_algebra/StructuredCospans.jl, test/categorical_algebra/StructuredCospans.jl
This PR was started from work by @Xiaoyan-Li. We can now use structured cospans to, for example, glue 2D simplicial sets along edges. (The unit tests show the slightly simpler case of 2D globular sets.)
=> Structured cospans of acsets with multiple objects in interface

src/programs/GenerateJuliaPrograms.jl, test/programs/GenerateJuliaPrograms.jl
Added a dictionary field to SimpleCompileState and a new kwarg to the `compile` method. If a generator name is in the keys, that symbol is replaced by the associated value in the `generator_expr` method.
=> Compile with generators

src/wiring_diagrams/MonoidalDirected.jl, test/wiring_diagrams/MonoidalDirected.jl
This small change allows the `permute` function to be called on wiring diagrams constructed by calling `to_wiring_diagram` on expressions over presentations of Free SMCs.
=> Bug fix for `permute` function

src/wiring_diagrams/Directed.jl
It's a graph, not a wiring diagram.
=> Type for graph underlying DWD has wrong supertype

src/theories/Schema.jl
If the presentation has no homs/attrs, then the type of `doms` passed to `SchemaDesc` is `Dict{Any,Any}` when `Dict{Symbol,Symbol}` is required by `SchemaDesc`. Just explicitly marking the type of the dictionary solves this.
=> Small fix for Presentation -> SchemaDesc function 

src/categorical_algebra/CSets.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/Limits.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/FinSets.jl, test/categorical_algebra/Limits.jl
I've found this construction useful in some other contexts, but this might be of general use.
This factors a morphism into a surjective map into an image and then an injective map into the codomain, where 'image' is defined in terms of limits (so this could be potentially applied in more general contexts than just CSetTransformations). 
Also included are `is_injective` / `is_surjective` test functions for CSetTransformations. (I'm not sure what those should do for attributes)
=> Epi mono factorization in terms of (co)limits

src/categorical_algebra/CSets.jl, src/categorical_algebra/FinSets.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/FinSets.jl, test/categorical_algebra/Limits.jl
Addressing both https://github.com/AlgebraicJulia/Catlab.jl/issues/684 and https://github.com/AlgebraicJulia/Catlab.jl/issues/683
=> Rename monic/epic and allow tight acset transformations

src/categorical_algebra/CSetDataStructures.jl, src/categorical_algebra/CSets.jl, test/categorical_algebra/CSetDataStructures.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/Diagrams.jl, test/categorical_algebra/Limits.jl
To avoid situations where `a==b` but `hash(a)!=hash(b)`, a hash method for C-Sets is added.
Addresses https://github.com/AlgebraicJulia/Catlab.jl/issues/656
=> Hash method for ACSets

src/acsets/DenseACSets.jl, src/categorical_algebra/DataMigrations.jl
These were triggering warnings during precompilation.
Follow up to #681.
=> Fix unused type parameters related to acset schemas

src/programs/DiagrammaticPrograms.jl, test/programs/DiagrammaticPrograms.jl
This refactor required a lot more work than I expected, but the improved design should be make it easier to maintain and extend the `@migration` macro and related macros.
=> Use intermediating AST in diagram macros

src/categorical_algebra/FinSets.jl, test/categorical_algebra/FinSets.jl
I'm not sure why Julia didn't throw an error here given the type constraint on `FinDomFunction`, but the issue can be avoided entirely since `FinFunction` and `FinDomFunction` are just type aliases for `SetFunction` subject to certain constraints.
=> Typo in type declaration of `FinDomFunctionDict`

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
We may want to take a limit, such as a pullback, on ACSets where we are actually only computing the limit of the *combinatorial* data. The question is how to handle the attributes in a canonical way: this is addressed by making the attributes of the apex of the limit to be the product of all* the attributes of objects in the diagram.
*: This is not strictly true: we only take the product of objects in the diagram which apex has legs into. Limits mathematically have legs into all objects of the diagram that we compute the limit of, but the `cone_obs` picks out specific objects for which we want to explicitly represent the legs to. This is typically the objects in the diagram which have no incoming morphisms.
=> Option `product_attrs` for ACSet limits 

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
The current backtracking search algorithm looks at the parts of a C-Set in a deterministic order. A keyword which shuffles this order could allow us to find a *single* morphism randomly without having to search for *all* morphisms and then pick one randomly.
=> Option to randomize C-set homomorphism search

src/graphics/GraphvizGraphs.jl, test/graphics/GraphvizGraphs.jl
This is a very small PR that just lets `to_graphviz` work with `node_labels` using labels that are Tuples. The reason this is useful is that some operations can change the types of labels on the resulting object. For example, taking the product of a `LabeledGraph{Symbol}` and `LabeledGraph{String}` results in a new label of type `Tuple{Symbol, String}`. This just makes the internal functions in the GraphvizGraphs module break those tuples down into a string for plotting, it's mostly useful for pedagogy.
=> Reformat Tuple node labels in Graphviz graphs

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
It can be very helpful when debugging to see why an ACSet transformation is unnatural. When the keyword `debug` is set to true, a list of violations is is returned. (This is type unstable, but `is_natural` shouldn't be used in a hot loop, anyways).
=> Add debug flag to `is_natural`

src/acsets/Schemas.jl, src/categorical_algebra/CSets.jl, src/categorical_algebra/CatElements.jl, src/categorical_algebra/StructuredCospans.jl, src/graphics/GraphvizGraphs.jl, test/categorical_algebra/CSets.jl
This extends the Struct vs Dynamic acset paradigm to include morphisms. Many features are still not covered for DynamicACSet categories, but this is a starting point. The goal of this PR was to be able to construct and compose maps between DynamicACSets.
=> Acset transformations between dynamic acsets

src/acsets/Schemas.jl, src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
This PR replaces the @generated functions with CompTime functions in `assign_elem!` and `unassign_elem!`. No noticeable performance regressions were observed (though this hasn't been rigorously tested).
=> Replace `@generated` code in homomorphism search with CompTime

src/acsets/DenseACSets.jl, src/categorical_algebra/CSets.jl, src/categorical_algebra/FinSets.jl, test/categorical_algebra/CSets.jl
This PR makes minimal changes in order to get working pushouts for dynamic acsets. `@ct_enable` is applied to `pack_colimit`,`colimit_attrs!`, and the top-level `colimit` call for a `DynamicACSet` first looks for an object in the diagram and then gets type information from that. For example:
```
diagram_ob(m::Multispan{DynamicACSet}) = apex(m)
diagram_ob(m::Multicospan{DynamicACSet}) = apex(m)
```
Right now only these diagrams are covered, but to support general colimits, every type that can serve as a diagram should be covered.
=> Colimits of dynamic acsets

src/acsets/ACSetInterface.jl
Fixed #728  by requiring that the parameter `acs` of acset part mutators be an actual `ACSet`.
=> Added type annotations to acset part mutators

src/categorical_algebra/FinSets.jl, src/categorical_algebra/Sets.jl, test/categorical_algebra/FinSets.jl, test/categorical_algebra/Sets.jl
Added checks that functions with explicitly given codomains actually have range in the codomain.
required adding in to typesets.
Also a little fiddling with which function constructors allow how many args; generally you should now never make it past FinFunction or FinDomFunction into the helper constructors without a codomain.
Fixes #751 .
=> Check that function data is compatible with codomains

src/acsets/ACSetInterface.jl, src/acsets/DenseACSets.jl, test/acsets/ACSets.jl, test/acsets/CSetDataStructures.jl
Removing a part with `recurse=true` removes all incident parts recursively
This can be redone much nicer after ACSets support 'mark as deleted'. Because deleting a single part changes the ids of other parts, a full pass must be made to find everything that must be deleted and then the deletion follows afterwards.
=> Cascading delete in acsets

src/categorical_algebra/FinCats.jl, src/programs/DiagrammaticPrograms.jl, test/categorical_algebra/FinCats.jl, test/programs/DiagrammaticPrograms.jl
Fixes #598 by having `@finfunctor` tell the user which morphisms are mapped inconsistently with the object map. There is code ready to update `@finfunctor` to check preservation of equations between morphisms in the domain category, too, once we have some ability to check equality of homs.
=> Improve finite functor error messages

.github/workflows/TagBot.yml
When a github action tags a release it doesn't trigger other github actions it doesn't look like, hopefully this resolves it. Mainly getting documentation to build when a tag is created by TagBot rather than being manually created.
=> Use AlgebraicJuliaBot to tag releases

src/acsets/ACSetInterface.jl, src/acsets/DenseACSets.jl, src/categorical_algebra/CSets.jl, src/categorical_algebra/FinCats.jl, src/categorical_algebra/Sets.jl, test/acsets/CSetDataStructures.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/FinCats.jl, test/categorical_algebra/Sets.jl
Closes #623 by defining macros @acset_transformation(s) that provide guardrails and syntax for construction of AcsetTransformations. Also refactors `is_natural` to be type-stable.
=> New macro `@acset_transformation`

src/acsets/DenseACSets.jl, src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
Implements a general purpose algorithm for calculating Most Common Sub C-Set
=> Maximum common sub-C-set

src/acsets/DenseACSets.jl, test/categorical_algebra/CSets.jl
delete_subobj! deletes part of an ACSet while returning the data needed to construct a morphism from the new into the old ACSet. This requires simulating how the indices change, and through more thorough testing I found an unnatural morphism being produced from the old code. 
This new version works for the new examples, and it appears to be more correct.
=> delete_subobj! bugfix

src/categorical_algebra/CSets.jl
Preparation for migration to ACSets.jl (#771), where presentations will not be available.
=> Serialize acset schemas as JSON via `Schema` rather than `Presentation`

docs/literate/sketches/cat_elements.jl, src/categorical_algebra/DataMigrations.jl, src/programs/DiagrammaticPrograms.jl, test/categorical_algebra/DataMigrations.jl, test/programs/DiagrammaticPrograms.jl
This PR separates `DataMigration`s from `DataMigrationFunctor`s. The former is currently just a functor from a schema to another schema or a category of diagrams in (diagrams in) a schema. For upcoming functionality, a `DataMigration` `M` contains a dictionary `params` intended to contain some Julia functions describing the attributes `migrate(X,M)` should have in terms of the attributes of `X`. The semantic reason for this change is that a data migration is not the same thing as a functor--the functor tells you how to migrate, but isn't identical to the migration. But it was forced, practically, by the need for those `params`. The existing `QueryDiagram`s handle the need for `param`s just fine when we're doing, well, queries, but not when we're doing mutations, as I'm working on …
=> Breaking change to data migration API

.github/workflows/benchmarks.yml, .github/workflows/reviewchecklist.yml
Not sure why the default `baseline` is not set to the default branch set in the git repo smh
=> BUILD: fix BenchmarkCI assumption that `origin/master` exists

docs/src/apis/categorical_algebra.md
I noticed two occurrences of this typo while reading the documentation, fixed them.
=> Fixed typos: colimts -> colimits

src/programs/DiagrammaticPrograms.jl, test/programs/DiagrammaticPrograms.jl
Resolves #805 .
The `leftmost_arg` function that's used to build `AST.Apply` and `AST.Coapply`s was missing a case for what to do when giving a composition operator that works in the opposite order of the target AST type.
=> Fix omitted case in `leftmost_arg`

src/categorical_algebra/CSets.jl, src/categorical_algebra/FinSets.jl, test/categorical_algebra/CSets.jl
This PR extends https://github.com/AlgebraicJulia/Catlab.jl/pull/808 to support negation / subtraction / implication for VarACSets.
Because monic VarFunctions are representable by FinFunctions, a lot of redundant code was eliminated by just treating the components of the AttrType parts the same as the Ob parts - the only care that's needed is to map over the components with `AttrVar` when constructing the ACSetTransformation components (and undoing this when going in the reverse direction).
=> More support for subacsets with variables

benchmark/Graphs.jl
The function `path_graph` creates a path graph in a "vectorized" style, making only one call to `add_edges!`.
Inspired by #822.
=> Benchmark two different implementations of making a path graph

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
Previously, the subobjects in order of decreasing size were computed as an iterator, but the partial overlaps between ACSets was computed all at once. However, for things like maximum common subacset, we are not interested in enumerating all possible overlaps, so this PR modifies the partial overlap computation to be an iterator.
=> Enumerating partial overlaps as an iterator

src/graphs/BasicGraphs.jl, src/graphs/GraphAlgorithms.jl, src/graphs/Searching.jl, test/graphs/BasicGraphs.jl
I guess this will technically be a breaking change but I'm pretty sure that my original implementation *did* return an iterator and it got changed somewhere along the way.
In the benchmarks on my local machine, we can see the "within a factor of 2 to 3" performance with Graphs.jl that we should expect. Previously, it was off by several orders of magnitude.
```
BenchmarkGroup:
10-element BenchmarkTools.BenchmarkGroup:
tags: []
"Graph" => 3-element BenchmarkTools.BenchmarkGroup:
tags: []
"LightGraphs" => 4-element BenchmarkTools.BenchmarkGroup:
tags: []
"iter-neighbors" => Trial(5.085 μs)
"iter-edges" => Trial(9.170 μs)
"make-path" => Trial(1.482 ms)
"has-edge" => Trial(28.376 μs)
"Catlab" => 4-element BenchmarkTools.BenchmarkGroup:
tags: []
"iter-neighbors" => Trial(14.507 μs)
"iter-edges" …
```
=> Make `neighbors` for graphs faster by returning an iterator

src/categorical_algebra/CatElements.jl, test/categorical_algebra/CatElements.jl
There was an unnecessarily strict typing on the the argument to `elements` which required it to be a `StructACSet` - this PR relaxes that constraint.
=> Category of elements for general C-sets

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
This branch has been tested with https://github.com/AlgebraicJulia/ACSets.jl/pull/32.
=> Forward compatibility for mark-as-deleted acsets

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
`abstract_attributes` is currently an unexported function. It takes an acset `X` and makes a map `A -> X` where `A` is 'all variables'. This is useful in AlgebraicRewriting. It might be more generally useful such that it should be an exported function. 
Regardless, the implementation in Catlab was broken and this PR fixes it and adds a test.
=> Fix `abstract_attributes` function

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
`ACSetTransformation(args...)` will try to deduce from the arguments whether it is a `Tight` or `Loose` transformation. It's a safe assumption that a Julia function for an attrtype means one wants a LooseACSetTransformation. This recovers pre-VarACSets behavior. Addresses https://github.com/AlgebraicJulia/Catlab.jl/issues/838
=> Infer LooseACSetTransformation when a Julia function is passed as a component

src/categorical_algebra/Chase.jl, src/categorical_algebra/FunctorialDataMigrations.jl, test/categorical_algebra/Chase.jl, test/categorical_algebra/FunctorialDataMigrations.jl
Functorial data migration should work on morphisms of ACSets too. It seems simple to work this out for delta - I'm not sure how other migrations might look. In the case of delta, it is straightforward to apply the functor to the domain and codomain and then copy the components (or type components) based on the data of the functor. 
One interesting thing I noticed is that it's not possible to apply a DeltaMigration to a LooseACSetTransformation `f: WeightedGraph{Int} -> WeightedGraph{Symbol}`, for example. This is because the data of a DeltaTransformation requires you to specify the concrete ACSet types, which means you can't apply the same DeltaMigration to both the domain and codomain of `f`.
=> Delta migration of acset transformations

src/categorical_algebra/FinCats.jl
I made `make_map` force the output to a specific type while writing `attrMigr`, a functionality which can cause all kinds of problems and was only actually being used in one quite narrow case. This PR resets it to the original functionality of only forcing the type for empty outputs.
=> Unbreak `makemap` from `attrMigr` branch

test/runtests.jl
Added two spaces on line 4 in runtests.jl to make it consistent with the other include statements.
Really really minor.
=> Consistent whitespace in runtests.jl

benchmark/Graphs.jl, src/categorical_algebra/CSets.jl, src/categorical_algebra/Chase.jl, src/categorical_algebra/HomSearch.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/Chase.jl, test/categorical_algebra/DataMigrations.jl, test/categorical_algebra/HomSearch.jl
By considering CSetTransformations between ACSets (where naturality is **not** demanded on attributes) we can obtain two sorts of practical constructions: 
1. A kind of "labeled CSet" where we can think of the attributes as functioning as labels
2. A kind of limit construction for ACSets which acts purely on the combinatorial data. The apex can put whatever it wants for the attributes, but we can deliberately *pick* a representative of the isomorphism class to make it correspond to something meaningful (with valid ACSetTransformations), which Kevin has a nice categorical characterization of in an AlgebraicJulia [blog post](https://blog.algebraicjulia.org/post/2023/06/varacsets/).
Implementation-wise, this means we want an abstract type of `ACSetMorphism` which is implemented by …
=> Transformations between acsets involving only combinatorial data

docs/literate/graphs/graphs_label.jl, docs/literate/sketches/meets.jl, docs/literate/sketches/preorders.jl, docs/literate/wiring_diagrams/wd_cset.jl, experiments/Markov/src/MarkovCategories.jl, experiments/Markov/src/StochExpr.jl, experiments/Markov/test/StochMapsExpr.jl, src/categorical_algebra/CatElements.jl, src/categorical_algebra/FinSets.jl, src/graphics/GraphvizCategories.jl, src/graphs/BipartiteGraphs.jl, src/graphs/PropertyGraphs.jl, src/theories/Theories.jl, src/wiring_diagrams/CPortGraphs.jl, src/wiring_diagrams/MonoidalDirected.jl, test/categorical_algebra/ACSetsGATsInterop.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/CatElements.jl, test/categorical_algebra/Categories.jl, test/categorical_algebra/Chase.jl, test/categorical_algebra/DataMigrations.jl, test/categorical_algebra/FinCats.jl, test/categorical_algebra/FinSets.jl, test/categorical_algebra/FunctorialDataMigrations.jl, test/categorical_algebra/StructuredCospans.jl, test/graphics/GraphvizCategories.jl, test/programs/GenerateJuliaPrograms.jl, test/programs/ParseJuliaPrograms.jl, test/theories/Theories.jl
Reexport GATlab from `Catlab.Theories` and thus also from `Catlab`. Closes #863.
=> Reexport GATlab

src/categorical_algebra/FinSets.jl
At some point I made the `FinFunction` method of `ensure_type_set_codom` return an explicit `SetFunctionCallable`, which causes explosions when it collides with vectors of `FinDomFunctionVector`s during `limit`.
=> Get rid of a bad use of SetFunctionCallable causing vector typing bugs

src/categorical_algebra/FinCats.jl
Just needed to expand a signature for the method of `id` relevant to attrtypes to make sure everything in a category presented by a schema with zero maps still has an identity morphism.
=> Adding missing `compose` and `id` methods for pointed set schemas

src/categorical_algebra/FunctorialDataMigrations.jl, test/categorical_algebra/FunctorialDataMigrations.jl
Add functionality and tests for building SigmaMigrationFunctors and yoneda embeddings with dynamic acsets. Before the methods of `SigmaMigrationFunctor` assumed that `constructor(X)` would be a `Type` for any acset `X`, but this is only true for `StructACSet`s.
This caused a bug for @aaguinal today so might be worth a patch release, though it's an easy workaround.
=> Add missing SigmaMigrationFunctor constructors for DynamicACSets

src/categorical_algebra/HomSearch.jl, test/categorical_algebra/HomSearch.jl
This constraint allows one to say, e.g. when searching for maps from the path graph with two edges into some big graph, that V2 *must* be sent to either vertex 2, 5, or 6 in the codomain, and that E1 *must* be sent to edge 3 or 7 in the codomain, etc. I.e. we have the option to restrict valid assignments to an arbitrary subset of the codomain for each part in the domain.
This is a required feature for my implementation of [incremental hom search](https://github.com/AlgebraicJulia/AlgebraicRewriting.jl/pull/36).
This is technically a generalization of the `initial` keyword argument, which would be `valid` assigning a singleton set to some part of the domain. However, the way that case is treated (immediately beginning hom search with that assignment) is very different from the general case …
=> Constrain acset hom search to specified subsets

src/categorical_algebra/CategoricalAlgebra.jl, src/categorical_algebra/SliceCategories.jl, test/categorical_algebra/CategoricalAlgebra.jl, test/categorical_algebra/SliceCategories.jl
Julia complains all the time now about Catlab and Base both exporting the word `Slices`. Can we just change the name? This would be a breaking change, not sure whether there's a better approach but I think leaving it as is isn't a serious option in that the attempted export wouldn't actually work if you tried to use `Slices` unqualified.
=> Rename `Slices` to `SliceCategories` to avoid name conflict

src/categorical_algebra/CSets.jl, src/categorical_algebra/HomSearch.jl, test/categorical_algebra/HomSearch.jl
Addresses https://github.com/AlgebraicJulia/Catlab.jl/issues/885 and https://github.com/AlgebraicJulia/Catlab.jl/issues/884.
=> Overlap iterator output span order bugfix + ignoring of specific attrtypes 

src/categorical_algebra/ACSetsGATsInterop.jl, src/categorical_algebra/CSets.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/HomSearch.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/HomSearch.jl
This branch incorporates [mark as deleted](https://github.com/AlgebraicJulia/ACSets.jl/pull/32) into Catlab. As was the case with VarACSets, the priority is getting support for hom search. Colimits would be the next natural thing to do. In the course of working on this, the problem of Catlab having it's own version of everything in ACSets (FinFunction machinery vs column + index machinery) was very painful. 
There could be no difference in the data structure for a morphism between MaD ACSets if we just treat the data in position `i` of a FinFunction (when `i` has been deleted in the domain) as to-be-ignored.  
Constructing the ACSetTransformation data structure (e.g. as the result of a hom search) posed a challenge, as the data gets validated in many ways which do not work when parts have …
=> Support for mark-as-deleted in acsets

src/categorical_algebra/HomSearch.jl, test/categorical_algebra/HomSearch.jl
Previously, subobject enumeration would error if performed on an ACSet with AttrVars. 
This PR implements the following behavior: when a subobject is taken such that certain AttrVars are no longer referred to, we remove those AttrVars from the subobject, too.
=> Enumerate subobjects of acsets with attribute variables

src/categorical_algebra/CSets.jl
Those words don't commute.
Minor text edit, so not that big a deal.
=> Fixed typo.  "commute must" -> "must commute".

src/categorical_algebra/CSets.jl, src/categorical_algebra/FinCats.jl
`DataMigrations.jl` uses the `dom_to_graph` function to convert a category from a presentation to a graph so that it can be fed into the `Limits` functionality. At the same time it has to do some typecasting to handle the fact that its diagrams might containing at least three concrete types--`SetFunctionCallable`,`SetFunctionId`,`FinDomFunctionInt`--while also allowing for mutations during the process of populating partially defined diagram and then constructing bipartite graphs for the limit. 
This PR modifies `dom_to_graph` to ensure that the output will always have `dom` a `FinCatGraph`, `ob_map` a vector of `obtype`, and `hom_map` a vector of `homtype`. There seems to be no reason as yet to allow `codom(F)` to be modified, although maybe there will be such a need someday.
Requesting a …
=> Simplify, upgrade, and type-stabilize dom_to_graph

src/categorical_algebra/ACSetsGATsInterop.jl
The current ACSetsGATsInterop file does not indicate how `subpart` called with a specific part (e.g. `Int`, `Vector{Int}`, `Colon`) behaves with respect to `id` or `generator` GATExprs. This PR adds this in.
This is necessary for compatibility with https://github.com/AlgebraicJulia/ACSets.jl/pull/130
=> Missing ACSetsGATsInterop methods

src/categorical_algebra/CSets.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/Limits.jl, test/categorical_algebra/CSets.jl
You can check for cartesian morphisms now! Just go like
```julia
is_cartesian(f,[h_1,h_2])
```
where `h_i == (name_i,src_i,tgt_i)` are triples of homs in the acset schema for the domain and codomain of `f`.
=> Cartesian transformations between acsets

src/categorical_algebra/CSets.jl
make kwargs argument match on lhs and rhs of method definition
=> Fix typo in `product` keyword arguments

src/categorical_algebra/FinSets.jl, src/categorical_algebra/Sets.jl, test/categorical_algebra/FinSets.jl, test/categorical_algebra/Sets.jl
The changes below are to enable smoother data migrations of acsets with some `AttrVar` attribute values as requested here: https://github.com/AlgebraicJulia/DataMigrations.jl/issues/159
=> Smoothing interaction between VarSets and actual sets and functions

src/categorical_algebra/CSets.jl, src/categorical_algebra/FinSets.jl
The subtraction operation was not brought up to date with AttrVar refactor, so a minor tweak is needed.
It uses `all_subparts`, which gets all the other parts that a part is referencing; however, that method searched over `homs` and not `arrows`. When this change is made, the correct behavior is recovered.
The relevance of this is that complement is used in this PR https://github.com/AlgebraicJulia/AlgebraicRewriting.jl/pull/62
=> Fix Heyting subtraction for ACSets with variables

src/categorical_algebra/CSets.jl, src/categorical_algebra/FinSets.jl, test/categorical_algebra/FinSets.jl
Modifications to make attrvars play nicer with data migrations. The key change in CSets is to redefine `ACSetFunctor`s, which are used critically in data migrations to compose with ordinary functors representing the migrations themselves, to again always take values in `FinSetInt`s and `FinDomFunction`s when possible. Previously, the `ACSetFunctor` of an `ACSet` containing any `Attrvar`s would take values entirely in `VarSet`s, which both confused the difference between actual `Attrvar`s and combinatorial data and interfaced badly with the `Limit`s API. 
To make this work I also defined how to compose `FinFunction`s with `VarFunction`s on the left.
=> Redesign ACSetFunctors when there are AttrVars

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
The constructor `(T)(::FinDomFunctor) where T<:ACSet` did not previously add any parts at `AttrType`s, which is necessary in case where some of the input's attributes take `AttrVar` values. We now add such `AttrVar`s, only when they're definitely needed, to avoid dangling `AttrVar`s, which are quite dangerous.
=> Fix constructor of acset from `FinDomFunctor` in varacset case

src/categorical_algebra/CSets.jl, src/categorical_algebra/FinSets.jl, test/categorical_algebra/CSets.jl
`(::Type{ACS})(F::FinDomFunctor)` would previously give back an `ACS{Any}` if `ob_map(F,:someAttr)` was a `VarSet` and an `ACS{Union{AttrVar,T}}` if `ob_map(F,:someAttr)` was `TypeSet{Union{AttrVar,T}}`.
=> Fix construction of varacset from `FinDomFunctor`

src/categorical_algebra/HomSearch.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/Chase.jl, test/categorical_algebra/HomSearch.jl
Addresses https://github.com/AlgebraicJulia/Catlab.jl/issues/916 in addition to addressing addressing the fact that the `monic` constraint keyword effectively would ignore AttrType components of the homomorphisms, which had the effect of:
1.) Returning morphisms which were technically not monic, if there existed matches which bound AttrVars in the domain to concrete values in the codomain
2.) Erroneously erroring due to "free floating variables" - we do not need to error for free floating variables if there is a monic constraint, since there are a finite number of possible assignments for each domain AttrVar in this case.
By default, homomorphism search can bind AttrVars to concrete values, but this will not be possible if `monic` or `no_bind` kwargs are turned on (either wholesale with …
=> Monic constraint and `no_bind` kwarg for AttrVars in hom search

src/categorical_algebra/FinSets.jl, test/categorical_algebra/CSets.jl
A recent change which makes iterating over VarSets return AttrVars rather than just integers introduced a bug in the complement operation for VarACSets (which gets used in AlgebraicRewriting/AlgebraicABMs). This fixes that and adds a test which calls complement on a VarACSet.
=> Bugfix for complement for VarACSets

Project.toml, docs/literate/graphics/graphviz_graphs.jl, docs/literate/graphs/graphs.jl, src/categorical_algebra/CSets.jl, src/categorical_algebra/CatElements.jl, src/categorical_algebra/FinSets.jl, src/categorical_algebra/HomSearch.jl, test/categorical_algebra/CSets.jl, test/categorical_algebra/Chase.jl, test/categorical_algebra/HomSearch.jl
This PR involves refactoring the `backtracking_search` interface, which now accepts `take`, `max`, and `filter` keyword arguments.
- `take` = number of homomorphisms requested (stop the search process early if this number is reached)
- `max` = throw an error if we find more than this many morphisms (e.g. set `max=1`  if one expects 0 or 1 morphism)
- `filter` = only consider morphisms which meet some criteria, expressed as a Julia function of type `ACSetTransformation -> Bool`
This allows `homomorphism` to be redefined as:
```julia
function homomorphism(X::ACSet, Y::ACSet, alg::BacktrackingSearch; any=false, kw...)
res = homomorphisms(X, Y, alg; Dict((any ? :take : :max) => 1)..., kw...)
isempty(res) ? nothing : only(res)
end
```
The old behavior is recovered via `any=true`, but this …
=> Require `homomorphism` to be unique

src/graphics/GraphvizGraphs.jl
The type in `to_graphviz_property_graph` is too narrow, the function calls down to the `PropertyGraph` constructor which is defined for type `HasGraph`.
=> Loosen type in `to_graphviz_property_graph`

src/programs/RelationalPrograms.jl, test/programs/RelationalPrograms.jl
Adds additional compatibility to typed UWDs to allow for Int types and Expr types. (Currently, only Symbol types are supported.)
=> Integer-typed UWDs

src/categorical_algebra/CSets.jl, test/categorical_algebra/CSets.jl
=> Informative error for `coerce_component` with scalar input

src/categorical_algebra/HomSearch.jl
Commit 3f95da1 introduced a regression for constructing Yoneda in the case of a schema that has an `AttrTypes` with no `Attrs` pointing to it, which surprisingly enough is sometimes useful (in case you want to migrate from a schema with `AttrTypes` to one without for migrations including code.) The problem was that `union` has no method for empty input since it can't decide on the output type, because typing Julia collections in empty cases is our entire job here. I fixed it.
=> Fix empty collection typing bug

src/graphics/Graphviz.jl
Since I mainly use Vim to develop, I don't have an embedded file viewer like VSCode so I wrote this snippet to visualize graphs in a floating window. But I'm opening this draft PR to open the discussion whether it should be upstreamed, and if so, what technical considerations.
I'm aware that `isdefined(Main, :VSCodeServer)` allows us to check if the REPL is being run in VSCode (and likewise for Juypter and IJulia), but I didn't write a validation to check that as I assumed a user would call this function in order to visualize the graph in a floating window.
1. Should `run` statements be used in code?
2. What other considerations besides operating system should a viewer check for? `feh` for example is not an image viewer everyone uses.
3. How can this code be generalized?
4. How can it be …
=> Floating viewer for Graphviz output

docs/literate/sketches/sheaves.jl, docs/make.jl, docs/src/apis/sheaves.md, src/Catlab.jl, src/sheaves/FVect.jl, src/sheaves/Sheaves.jl, test/runtests.jl, test/sheaves/sheaves.jl
This PR adds a module for sheaves, including abstract types. It has an example for free vector space as a sheaf over Diag(FinSet).
=> Add Sheaf implementation 

src/categorical_algebra/FinRelations.jl, src/categorical_algebra/FinSets.jl, src/wiring_diagrams/Algebras.jl
- The `in` functions were not really causing problems, since Julia was defaulting to iterating over the container. However, it was creating method ambiguities (I caught it with Aqua).
- In the function `make_homomorphism` the comprehension `[row[i+=1] for _ in parts(X,c)]` is creating a vector of type `Any` if `parts(X, c)` is empty.
=> Fix bugs in `Base.in` methods and empty comprehension

src/graphics/GraphvizGraphs.jl, src/graphics/GraphvizWiringDiagrams.jl
PR #570 added titles to DWDs. I tried to ape what was there to support titles for UWDs.
Example output:
```julia-repl
julia> compose_klausmeier = @relation () begin
phyto(N, W)
hydro(N, W)
end;
julia> b = Catlab.Graphics.Graphviz.Label("Foo", "Klausmeier");
julia> Catlab.Graphics.Graphviz.view_graphviz(to_graphviz(compose_klausmeier, title=b, box_labels=:name, junction_labels=:variable, prog="circo"))
Process(`open /var/folders/0j/9wfk7fvn41b1bskzfrh85m240000gq/T/jl_HSHaPKd4Ts.png`, ProcessRunning)
```
=> Add titles to uwds

.github/workflows/downstream.yml
To prevent problems with DiagrammaticEquations.jl when we update Catlab.
=> add DiagrammaticEquations.jl to downstream.yml
